### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#100]
Hello,

I am trying to install OpenBazaar for the first time but [without success](https://github.com/OpenBazaar/OpenBazaar-Client/issues/218#issuecomment-165595933)

```
$ make
...
Traceback (most recent call last):
  File "/usr/bin/pylint", line 3, in <module>
    run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 21, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 1012, in __init__
    linter.load_config_file()
  File "/usr/lib/python2.7/dist-packages/logilab/common/configuration.py", line 662, in load_config_file
    provider.set_option(option, value, optdict=optdict)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 392, in set_option
    meth(_id)
  File "/usr/lib/python2.7/dist-packages/pylint/utils.py", line 276, in disable
    msg = self.check_message_id(msgid)
  File "/usr/lib/python2.7/dist-packages/pylint/utils.py", line 341, in check_message_id
    raise UnknownMessage('No such message id %s' % msgid)
pylint.utils.UnknownMessage: No such message id W1608
FAIL: Detected 50 files with errors.
make: *** [pycheck] Error 1
```

----

Also the README says I need to install `python-pylint-common` but I get

```
E: Unable to locate package python-pylint-common
```

then I found the on Ubuntu I need to run http://www.pylint.org/#install

```sh
sudo apt-get install pylint
```

----

Also `pip install -r requirements.txt` failed 
then I tried `sudo pip install -r requirements.txt` and it worked.

**Comment by hoffmabc** [comment]
Have you tried the Debian packages I published?

**Comment by moldcraft** [comment]
No, can you give me a link?

**Comment by hoffmabc** [comment]
https://files.slack.com/files-pri/T02FPGBKB-F0GRG3RA4/openbazaar_0.1.0-1_amd64.deb

**Comment by cpacia** [comment]
you shouldn't need to run `make` it's really just used for running tests.

**Comment by moldcraft** [comment]
*I should find [this page](https://github.com/OpenBazaar/OpenBazaar-Server/wiki/How-to-install-on-Ubuntu) earlier...*

> @hoffmabc https://files.slack.com/files-pri/T02FPGBKB-F0GRG3RA4/openbazaar_0.1.0-1_amd64.deb

Thank you. But it doesn't want to install. It shows [this](https://static.md/6b30d151342cd6b7a63e5992b2f6a59e.png), the I press "Ignore and install", it loads then [the "Install" button appears again](https://static.md/42ece16e341af3733b22b08921688174.png), I pressed "Install" the second time, but the same cycle happens

> @cpacia you shouldn't need to run make it's really just used for running tests.

Sorry, I am a bit newbie in compiling, I just follow the steps. 
You are right, I executed `python openbazaard.py start` and it started. Thank you!

----

So the server is running, I tried to install the client `npm install` but I got

```
...
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm ERR! not ok code 0
```

I deleted `sudo rm -rf node_modules/` and tried again, while installing I got

```
> spawn-sync@1.0.13 postinstall /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/node_modules/pre-commit/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> pre-commit@1.1.2 uninstall /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/node_modules/pre-commit
> node uninstall.js

sh: 1: node: not found
npm WARN continuing anyway undefined
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! Error: ENOENT, lstat '/home/m/tmp/npm-745-Pztix00o/1450394792673-0.380222249077633/package/assets/yui/yahoo-dom-event.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/m/tmp/npm-745-Pztix00o/1450394792673-0.380222249077633/package/assets/yui/yahoo-dom-event.js
npm ERR! fstream_path /home/m/tmp/npm-745-Pztix00o/1450394792673-0.380222249077633/package/assets/yui/yahoo-dom-event.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/m/tmp/npm-745-Pztix00o/1450394791211-0.2695156231056899/package
npm ERR! addLocalDirectory Could not pack "/home/m/tmp/npm-745-Pztix00o/1450394791211-0.2695156231056899/package" to "/home/m/.npm/handlebars/4.0.5/package.tgz"
....
```

then the installation continued until it stopped with

```
> electron-prebuilt@0.34.2 postinstall /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/npm-debug.log
npm ERR! not ok code 0
```

then I executed `npm install electron-prebuilt` and I got

```
> electron-prebuilt@0.36.0 postinstall /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
```

**Comment by cpacia** [comment]
try doing 
`sudo apt-get install nodejs-legacy`
then
`sudo npm install`

Also run the server using `python openbazaard.py start --testnet`

**Comment by SamPatt** [comment]
@moldcraft I'm a bit late to the party but here are the updated instructions for manual installation of the client on Ubuntu:

https://docs.google.com/document/d/1qgXRLuNRB2vDJHEjLR03yUxCcztS2tiliGPozEiedac/edit?usp=sharing

**Comment by moldcraft** [comment]
I noticed the error

```
sh: 1: node: not found
```

I installed `sudo apt-get install node` and executed `npm install`

while installing I got

```
> electron-prebuilt@0.34.2 postinstall /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/node_modules/electron-prebuilt
> node install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

it continued until it stopped with

```
npm http 304 https://registry.npmjs.org/wrappy
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client/npm-debug.log
npm ERR! not ok code 0
```

`npm-debug.log`

```
12131 error EEXIST, mkdir '/home/m/tmp/npm-1794-waQC8Lnf/1450395437367-0.1336660364177078/package/test/3rdparty'
File exists: /home/m/tmp/npm-1794-waQC8Lnf/1450395437367-0.1336660364177078/package/test/3rdparty
Move it away, and try again.
12132 error System Linux 3.19.0-30-generic
12133 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
12134 error cwd /home/m/Downloads/OpenBazaar-Installer-master/OpenBazaar-Client
12135 error node -v v0.10.25
12136 error npm -v 1.3.10
12137 error path /home/m/tmp/npm-1794-waQC8Lnf/1450395437367-0.1336660364177078/package/test/3rdparty
12138 error fstream_path /home/m/tmp/npm-1794-waQC8Lnf/1450395437367-0.1336660364177078/package/test/3rdparty/backbone-0.5.3.js
12139 error fstream_type File
12140 error fstream_class FileWriter
12141 error code EEXIST
12142 error errno 47
12143 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
12143 error fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
12143 error fstream_stack Object.oncomplete (fs.js:107:15)
12144 verbose exit [ 47, true ]
```

Sorry for all those big logs, I just want to share all problems I encountered.

----

I installed `sudo apt-get install nodejs-legacy` then `sudo npm install`, then `npm start` and it started. Thank you all for fast responses!

**Comment by ABISprotocol** [comment]
A suggestion:  It seems that the installation details at https://github.com/OpenBazaar/OpenBazaar-Server/wiki/How-to-install-on-Ubuntu are not easy to find, and could better be moved as a link to the Readme at https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/README.md -- and at https://github.com/OpenBazaar/OpenBazaar-Installer
Definitely other OS's (Windows, MacOSX) could use a link that takes you to a description of how to get through the install process, also.

Additional note:

According to https://github.com/OpenBazaar/OpenBazaar-Server/issues/98 for fresh Ubuntu,
sudo pip install service_identity
(is supposed to be put in after)
sudo pip install -r requirements.txt

Currently it appears as
sudo -H pip install -r requirements.txt
sudo -H pip install -r test_requirements.txt

This could be fine, but just observing this difference after having reviewed https://github.com/OpenBazaar/OpenBazaar-Server/issues/98

TY

**Comment by ABISprotocol** [comment]
@cpacia @moldcraft Seems this issue merits opening again?  Being as there should be a pull request associated with it soon (to make the installation details more simple and not so crazy)

**Comment by moldcraft** [comment]
I decided to give it a try again. And again the installation is frustrating

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o

build/temp.linux-x86_64-2.7/_openssl.c:425:25: fatal error: openssl/aes.h: No such file or directory

 #include <openssl/aes.h>

                         ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3uux_V-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 67: ordinal not in range(128)
```

When README.md will be updated with good installation instructions?

**Comment by moldcraft** [comment]
```sh
sudo apt-get install libssl-dev
```

fixes the problem. 

But... every time someone will try to install OpenBazaar he will face the same problems. You should add in README.md all requirements needed to be installed before doing the actual OpenBazaar install

**Comment by moldcraft** [comment]
Install went ok, I tried to start it and fail ...

```
$ python openbazaard.py start --testnet
Traceback (most recent call last):
  File "openbazaard.py", line 28, in <module>
    from net.sslcontext import ChainedOpenSSLContextFactory
  File "/home/m/Soft/OpenBazaar-Server/net/sslcontext.py", line 2, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
```

**Comment by moldcraft** [comment]
I'll better wait a few months until v1.0 will be released.

**Comment by hoffmabc** [comment]
We are currently working on all installers and the process. This started with the OSX and Windows where the majority of our users will reside. Linux is next and will improve soon. We also just recently changed some critical libs in the last week and haven't updated the README yet.

**Comment by BazaarBay** [comment]
You can get it installed on Ubuntu 14.04 but it's going to be bit painful. But if you've got a few evenings to spare and required skills, no problem. I've done it. I'm not expert, so it took quite a while to get everything to work.

**Comment by tyler-smith** [comment]
For that "No module named cryptography.hazmat.bindings.openssl.binding" error, you should be able to `sudo apt-get install libffi-dev` and then `pip install -r requirements.txt` again one more time and that should fix it.

I am using OpenBazaar on Ubuntu 14.04 with no issues. I'll try to go through the README and update anything I found that's out of date.

**Comment by moldcraft** [comment]
Thank you guys for fast reply. I'll give it a try in a few days. It will be nice if you will announce when the improvements will be done in slack, I receive email notifications when you post with `@channel`.

> @tyler-smith `sudo apt-get install libffi-dev`

I have it already installed.

**Comment by ABISprotocol** [comment]
@hoffmabc @moldcraft Please see [this issue and comment(s)](https://github.com/OpenBazaar/OpenBazaar-Installer/issues/16#issue-130515240) also.  Additional remarks / pull request soon to follow, this needs some improvement obv.  In part as I mentioned [here](https://github.com/OpenBazaar/OpenBazaar-Server/issues/100#issuecomment-174113033) the installation details and _full_ instructions are not easy to find straight from whatever README you are looking at and it's too confusing to the average user.  This needs to be straightened out / simplified.
