### ISSUE TITLE
purchase_contract does not add moderator fee

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#105]
When the moderator guid is sent to purchase_contract, the price that is returned is the item price times the quantity, without the moderator fee added. 

Ex: if a quantity of 8 of an item that costs 0.001 BTC is purchased, with a moderator fee of 10%, the price returned is 0.008 BTC instead of 0.0088 BTC.

**Comment by cpacia** [comment]
I thought the fee was taken out of the sale price?

**Comment by hoffmabc** [comment]
It is.

**Comment by jjeffryes** [comment]
Ah, my bad. I misunderstood that part.

I'll update the client to match that.
