### ISSUE TITLE
Exception with get_chat_messages

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#107]
The API call `http://localhost:18469/api/v1/get_chat_messages` give the following traceback:

![screen shot 2016-01-01 at 17 31 59](https://cloud.githubusercontent.com/assets/731743/12071642/da3085fc-b0ad-11e5-8b58-c5ba97e7a2f2.png)

**Comment by hoffmabc** [comment]
You need to pass a GUID of the user you want chat messages for.

**Comment by JustinDrake** [comment]
@hoffmabc Ok, stupid me. Throwing an exception isn't great though.
