### ISSUE TITLE
Which paper is being referred to?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#112]
It seems a paper regarding DHTs is being referenced in the code. ("per section 2.5 of the paper", "per section 2.3 of the paper", etc.)

What paper is being referenced? This one: https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf?

**Comment by cpacia** [comment]
The original kademlia paper
