### ISSUE TITLE
Seed node redundancy

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#114]
Looking into `ob.cfg`, it seems there is only a single seed node `SEED_NODE = 205.186.154.163:18467`. (BTW, who maintains this node?)

Having a single seed node introduces a single point of failure (in particular, high exposure to DDoS).

**Comment by moldcraft** [comment]
btw: A few days ago I tried to start OpenBazaar Server but it failed because it wasn't able to contact the seed node.

**Comment by cpacia** [comment]
That SEED_NODE should probably be renamed. It's really a relay node for hole punching (which run on the same server as our seed), but eventually we will need more redundancy.
