### ISSUE TITLE
Documenting changes made to bmuller's Kademlia

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#116]
OpenBazaar's implementation of Kademlia is taken from https://github.com/bmuller/kademlia/tree/master/kademlia, and seems to be very similar.

Are the differences between the two implementations documented? That would made understanding OpenBazaar's implementation of Kademlia easier to understand.

**Comment by cpacia** [comment]
They aren't documented anywhere. This differences are quite large at this point.
