### ISSUE TITLE
Documenting RPC calls

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#117]
OpenBazaar has 8 RCP messages. I'm trying to wrap my head around them.

* PING, STORE, FIND_NODE, FIND_VALUE are described in the Kademlia paper
* STUN, HOLE_PUNCH seem to be NAT related
* DELETE seems to be to delete key-value pairs from the DHT
* What are INV, VALUES?

Where are RPC calls documented?

**Comment by cpacia** [comment]
There aren't documented anywhere. 

The INV/VALUES works like INV/GETDATA in bitcoin. Instead of bombarding a node with store requests for data it might already have, it sends an INV packet with hashes and the node requests only those hashes it needs. Which are sent in the VALUES packet.
