### ISSUE TITLE
Search should display items from my store

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Server#123]
As a vendor, I'd like to see my items returned when I perform a matching search. Currently, it seems as if my keywords aren't working because my items do not display when I search for them via the keywords I set.

**Comment by SamPatt** [comment]
I constantly get requests from vendors testing who want to be able to see their store and items as their customers see them, so I agree this would be helpful for them.

**Comment by jjeffryes** [comment]
This is how it works now. I can search on my own items, and they show up normally. 

Mike, make sure you have the latest server, and then edit each of your items. Chris made changes to the contracts that will cause old items not to always work unless they've been edited, which will update them to the new contract.

**Comment by morebrownies** [comment]
Nice! yeah seems to work on new items :)

**Comment by morebrownies** [comment]
I take that back. It seems to work on some new items, but not on others. There's definitely some weirdness associated to seeing my own items come up in search.

**Comment by morebrownies** [comment]
Possibly there is a delay or something? not sure..
