### ISSUE TITLE
Cache NAT type

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#134]
On bootup the client spend a lot of time (~10 seconds) on

```
[INFO] Finding NAT Type...
```

Is it possible to cache the NAT Type to avoid this initial wait time?

**Comment by cpacia** [comment]
The nat type can be cached but there is no way to know if it changes if we do that.

**Comment by JustinDrake** [comment]
Would it be possible to add a cache for development? I'm quitting and restarting the client often, and this would be a big help.

**Comment by drwasho** [comment]
I think figuring out the type of NAT is too important to skip over, especially when people are going to be reporting bugs related to connectivity and we need the NAT type to be accurate in their logs.
