### ISSUE TITLE
Can a node know if it has been banned?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#137]
If my node was banned by another node, is there a way for my node to find out that it has been banned?

**Comment by hoffmabc** [comment]
I think from a malicious standpoint you don't want to tell nodes they're banned as they will continue to operate in a failed state and not decide to adjust their attack and avoid the ban.

**Comment by JustinDrake** [comment]
What if the ban is accidental? When a node is banned, the banning node can inform about the ban, and later ignore all requests. That seems like a good compromise.

**Comment by JustinDrake** [comment]
@cpacia A comment would be helpful.
