### ISSUE TITLE
Publish GUID on bootup

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#139]
During the testing period it would be useful to have the GUID of the node be printed out in the console at bootup.

**Comment by tcharding** [comment]
diff --git a/keys/keychain.py b/keys/keychain.py
index 1e8fe88..8cc953c 100644
--- a/keys/keychain.py
+++ b/keys/keychain.py
@@ -49,4 +49,3 @@ class KeyChain(object):
         self.encryption_key = self.signing_key.to_curve25519_private_key()
         self.encryption_pubkey = self.verify_key.to_curve25519_public_key()
         callback(self, True)
-
diff --git a/openbazaard.py b/openbazaard.py
index 8cc0647..1ea47d9 100644
--- a/openbazaard.py
+++ b/openbazaard.py
@@ -176,7 +176,8 @@ def run(*args):
         reactor.listenTCP(HEARTBEATPORT, WebSocketFactory(heartbeat_server), interface=interface)
 
     # key generation
-    KeyChain(db, start_server, heartbeat_server)
+    keychain = KeyChain(db, start_server, heartbeat_server)
+    print "GUID: %s" % hexlify(keychain.guid)
 
     reactor.run()

**Comment by tcharding** [comment]
OW , markdown hates diff

**Comment by drwasho** [comment]
@cpacia

**Comment by JustinDrake** [comment]
@cpacia A comment would be helpful.
