### ISSUE TITLE
Accept incoming connections

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#146]
Every time I launch the server I have to 'Allow' incoming connections. Is there a way to allow incoming connections once and for all?

![screen shot 2016-01-19 at 11 25 22](https://cloud.githubusercontent.com/assets/731743/12417375/9da07f70-be9f-11e5-9dac-2391f8e53fc9.png)

**Comment by JustinDrake** [comment]
I think signing the software with a valid certificate authority would do the trick.

**Comment by hoffmabc** [comment]
We will be signing official releases and this should go away. That being said you shouldn't keep seeing this message.
