### ISSUE TITLE
Could not find txrudp==0.5.0

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#147]
I've just pulled the latest version, and `pip install -r requirements.txt` is failing with the following error:

```
Could not find a version that satisfies the requirement txrudp==0.5.0 (from -r requirements.txt (line 3)) (from versions: 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.1)
No matching distribution found for txrudp==0.5.0 (from -r requirements.txt (line 3))
```

**Comment by hoffmabc** [comment]
We were testing a new package and while testing pypi I removed 0.5.0. Until we upgrade requirements.txt you can bump to 0.5.1.

pip install txrudp==0.5.1
