### ISSUE TITLE
Delete database while preserving GUID

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#149]
I'm trying to debug a problem with the db cache, and I'm deleting `~/OpenBazaar` quite a bit. For debugging, having to wait for the GUID to regenerate is frustrating. Is there a way to delete the database while preserving my GUID?

**Comment by drwasho** [comment]
I think the only way is to open Sqlite browser, copy and paste the GUID + private keys in a separate text file that you can input into a newly created db? Not sure if that will work.
