### ISSUE TITLE
Unhandled errors silently thrown

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#157]
I am developing on top of the OpenBazaar-Server, and for some reason my unhandled errors are not shown in the console. I expect it has something to do with Twisted.

How can I get my Python errors to show in the console?

**Comment by hoffmabc** [comment]
The only way to bump up logging at this time is to make sure you set -l debug on startup of the server, which I believe is default at this time.

Pinging @cpacia to confirm.

**Comment by JustinDrake** [comment]
@hoffmabc: I'm referring to unhandled Python exceptions which seem hidden away.

**Comment by hoffmabc** [comment]
If it's Twisted I'm not sure there's much we can do on our end.

**Comment by cpacia** [comment]
All you can do is use try/except with
```
import traceback
traceback.print_exc()
```
