### ISSUE TITLE
Server fails to start, no reason logged

### ISSUE THREAD

**Issue by BazaarBay** [OpenBazaar/OpenBazaar-Server#165]
Even if **debug log** is enabled, reason why server **start fails** is not getting logged.
```
2016-01-24 ##:##:##+0000 [OpenBazaard] [INFO] Finding NAT Type...
2016-01-24 ##:##:##+0000 [OpenBazaard] [INFO] Full Cone on #.#.#.#:#
```
Reason for server start fail also seems random, because next start attempt can work or not. So there's no local configuration / db / issue which is causing the failure.

**Comment by cpacia** [comment]
I think this is resolved
