### ISSUE TITLE
OpenBazaard hang if multiple processes running

### ISSUE THREAD

**Issue by tcharding** [OpenBazaar/OpenBazaar-Server#175]
If another instance of openbazaard is running in the background then a startup in the foreground hangs without a warning message. 

https://openbazaar.slack.com/archives/openbazaar-server/p1453852739000245

patching as @tyler-smith suggests points to the problem but a warning that just plain states it would save others time.

**Comment by tyler-smith** [comment]
Personally I think this should probably have 1) a small sleep between iterations and 2) a maximum number of attempts before giving up. Or at the very least, a warning that displays in the logs if it's been trying longer than X minutes. Just to give people some indication of what's wrong.

**Comment by drwasho** [comment]
Maybe you can take a stab at this @tcharding?

**Comment by tcharding** [comment]
PR #215 addresses this issue
