### ISSUE TITLE
Server fails to start!!

### ISSUE THREAD

**Issue by neogeo1988** [OpenBazaar/OpenBazaar-Server#178]
ubuntu@ip-172-30-2-13:~/OpenBazaar-Server$ python openbazaard.py start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Exception : No UPnP device discovered
2016-01-27 12:30:42+0000 [OpenBazaard] [INFO] Finding NAT Type...
2016-01-27 12:30:42+0000 [OpenBazaard] [INFO] Full Cone on 52.90.89.7:18467
Traceback (most recent call last):
  File "openbazaard.py", line 257, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 182, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 232, in start
    int(args.restapiport), int(args.websocketport), time.time())
  File "openbazaard.py", line 89, in run
    storage = ForgetfulStorage() if TESTNET else PersistentStorage(db.DATABASE)
  File "/home/ubuntu/OpenBazaar-Server/dht/storage.py", line 147, in __init__
    self.db = lite.connect(filename)
ValueError: database parameter must be string or APSW Connection object
ubuntu@ip-172-30-2-13:~/OpenBazaar-Server$

**Comment by hoffmabc** [comment]
Make sure if you have a folder named ~/OpenBazaar you move or delete it and restart the server.

**Comment by neogeo1988** [comment]
i have ...and the same resulat!!!...i even made a virtual box fresh..the same thing there

**Comment by cpacia** [comment]
Did you run it with the --testnet flag?

**Comment by neogeo1988** [comment]
with --testnet works....i wanted normal start or with -a 0.0.0.0
.
