### ISSUE TITLE
Moderator Fee is Changed by Server

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#180]
When I send a moderator fee of 0.1, it is returned by the server as 0.10000000149011612.

A fee of 5.1 is returned as 5.099999904632568

I'm assuming this is a floating point rounding issue, should the value be multiplied by 1000 first, or should we disallow the decimal point?

**Comment by cpacia** [comment]
This is in the profile?

**Comment by jjeffryes** [comment]
This issue is still occurring, a fee of 1.01 when saved is returned as 1.0099999904632568

**Comment by drwasho** [comment]
Was this fixed in commit [0e29ccd](https://github.com/OpenBazaar/OpenBazaar-Server/commit/0e29ccdf46cefb06ba6165fbc84de77cd77d2e30) @cpacia ? Can we close this?
