### ISSUE TITLE
API fails with "no such column: tempHandle"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#184]
The example `http://localhost:18469/api/v1/profile?` fails with "no such column: tempHandle"

![screen shot 2016-01-31 at 17 11 51](https://cloud.githubusercontent.com/assets/731743/12703259/26199be0-c83f-11e5-9955-6f918b0b22b8.png)

**Comment by hoffmabc** [comment]
I believe you will need to blow away and recreate the db or create a column called tempHandle.

**Comment by JustinDrake** [comment]
How can I add a column, so that I can keep my precious store?

**Comment by hoffmabc** [comment]
You will need to use a SQLite browser/editor for your OS
