### ISSUE TITLE
Option to backup database

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Server#186]
Both the database itself and all the data in the folder need to be able to be backed up easily.

This issue is also opened on the client side:

https://github.com/OpenBazaar/OpenBazaar-Client/issues/633

**Comment by tyler-smith** [comment]
You say "all the data in the folder", but I'm wondering if this include cache data or not. It seems to me that for a backup, not including cache data would be ideal. The rational being that backups are typically for long term storage and the cache would be likely be largely invalid.

**Comment by cpacia** [comment]
Yeah cache probably isn't needed. It's pretty easy to use the dropbox python api. The only issue would be finding all the spots in the code where a backup should be triggered.

**Comment by tyler-smith** [comment]
Interesting. I was imaging on-demand backups. I.e. a button in Settings or something. Automatic backups could be cool. It would need to maintain a few over time I think so it doesn't get updated to a state people would like to revert from.

**Comment by cpacia** [comment]
yeah

**Comment by bdunbar** [comment]
Backup triggered by API?  I love it.

Are we talking local backups, backing up to DropBox, other?

One should make a provision for deleting backups older than X, if stored locally.  More than a few people will never, ever, delete backups until their disk is full and OB doesn't run.

Have a customer.  We inherited management of their sprawling crowd of servers.  One IIS host has 18gb of backup web logs, carefully archived, going back to 2010.  No one knows why ...

**Comment by tyler-smith** [comment]
I think on-demand backups are very ideal. Automated periodic backups would be cool too, and I agree being able to configure the amount retained would be great, but I think a API endpoint to create a backup is necessary long term.

IMO it would be cool if the backend to save to was configurable defaulting to a local directory. But allowing for Dropbox or whatever people are using these days.

At any rate, starting with an on-demand version seems like a good first step.

**Comment by drwasho** [comment]
I'd be happy to start with Dropbox and close this issue... We can build on that in future releases.

**Comment by jjeffryes** [comment]
We've currently decided not to add this feature.

**Comment by bdunbar** [comment]
@jjeffryes 'decided not to add this feature' does this apply to 1.0 or to 2.0?

**Comment by tyler-smith** [comment]
@bdunbar Just 1.0

**Comment by bdunbar** [comment]
Thanks!

**Comment by xeddmc** [comment]
Does that mean that 2.0 will have the option?

**Comment by jjeffryes** [comment]
Yes. We're planning to add a database backup feature in 2.0.
