### ISSUE TITLE
HTML escaping causes malformed profile response

### ISSUE THREAD

**Issue by justicz** [OpenBazaar/OpenBazaar-Server#188]
If you set the username on a social account to a string containing special characters, something goes very wrong ([probably around here](https://github.com/OpenBazaar/OpenBazaar-Server/blob/2cc1a372a72da680ce50766b6da09059d957dab5/api/restapi.py#L141)) and causes the profile endpoint to return invalid json:

```"instagram": {
                "username": "\"&gt;&lt;test", "proof_url":="" ""="" }="" },="" "moderation_fee":="" 10.0,="" "moderator":="" false,="" "nsfw":="" false,="" "handle":="" "",="" "guid":="" "7c0c581c5224f22f41d0218998a12e98f1ee361a",="" "background_color":="" 407379,="" "secondary_color":="" 3243448,="" "location":="" "na",="" "short_description":="" "test\"=""&gt;&lt;"```

**Comment by cpacia** [comment]
What special characters are you trying to put in?

**Comment by justicz** [comment]
In this case I set my instagram username to `"><test`.

**Comment by cpacia** [comment]
Probably just need to check it client side @jjeffryes

**Comment by justicz** [comment]
I don't think you should ever be able to get the server to reply with invalid json -- this definitely seems like a server bug to me.

**Comment by jjeffryes** [comment]
We will need to do sanitization on both sides, server and client, since you can send data directly to the server without a client (or with a custom client). 

We'll need a fairly robust whitelist solution, one that strips all non-alphanumeric or punctuation characters but allows whitelisted tags. The currently allowed tags in the client are 
'h2','h3', 'h4', 'h5', 'h6', 'p', 'a','u','ul', 'ol', 'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'hr', 'br', 'img', 'blockquote'

**Comment by jjeffryes** [comment]
I put in an issue on the client side to extend sanitizing to all inputs.

**Comment by justicz** [comment]
Okay, but we should definitely deal with this issue of the server returning a malformed response. This: ` "proof_url":="" ""="" }=""` should never happen.

**Comment by jjeffryes** [comment]
Agreed on preventing malformed responses. That's Chris's department.

**Comment by BazaarBay** [comment]
It's also possible to add / modify data directly in database or line protocol between servers via modified or completely custom server code. All of those things need to be counted.

**Comment by drwasho** [comment]
I think this has been fixed @cpacia ?

**Comment by drwasho** [comment]
Fixed
