### ISSUE TITLE
Profile API request returns {} for buyers. Is this the intended behaviour?

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#192]
http://localhost:18469/api/v1/profile?guid=0f912958d71ec44ce69fdecb947dc7b907f38b08

for example, returns {}, where 0f912958d71ec44ce69fdecb947dc7b907f38b08 is a new node that has not opted to set up as a store (i.e. is just a buyer).

Is this the intended behaviour? It's not documented here: https://docs.google.com/document/d/1IZQQBw-LpMFFTk6T76ENZ4z5LVEkM5LDm9Qb8c-YoKo/edit

**Comment by cpacia** [comment]
{} is returned at the moment if it can't connect to that node.

**Comment by dsmurrell** [comment]
Does it fail to connect if the node hasn’t set up as a store, or does that have nothing to do with anything?
Do you have any guids of nodes that aren’t stores but that you get a response from? (i.e. it connects and you get a profile)

**Comment by drwasho** [comment]
@dsmurrell the new API documentation will be updated to indicate that `{}` will be returned if the node isn't online.
