### ISSUE TITLE
DATA_FOLDER created with world write

### ISSUE THREAD

**Issue by tcharding** [OpenBazaar/OpenBazaar-Server#200]
If openbazaard is started in daemon mode (-td) without a DATA_FOLDER then newly created directory has permissios 777. Does not happen if 'd' option is not passed in.

**Comment by tcharding** [comment]
One solution would be to create an Database instance before the main process daemonizes (if the data_folder does not exist). 

diff --git a/openbazaard.py b/openbazaard.py
index 6eb7c7a..64d2b59 100644
--- a/openbazaard.py
+++ b/openbazaard.py
@@ -34,7 +34,7 @@ from protos.objects import FULL_CONE, RESTRICTED, SYMMETRIC
 from twisted.internet import reactor, task
 from twisted.python import log, logfile
 from txws import WebSocketFactory
-
+import os
 
 def run(*args):
     TESTNET = args[0]
@@ -243,6 +243,9 @@ commands:
 
             unix = ("linux", "linux2", "darwin")
 
+            if not os.path.exists(DATA_FOLDER):
+                Database(TESTNET)
+
             if args.port:
                 port = int(args.port)
             else:

**Comment by tcharding** [comment]
Can't work out why markdown is making that import a large font :)

**Comment by drwasho** [comment]
@tcharding and @cpacia what's the status on this?

**Comment by saltduck** [comment]
I make a commit, change the permission to 0750. See PR #276

**Comment by drwasho** [comment]
Seems to be fixed based on #276.
