### ISSUE TITLE
Prevent duplicate queries of unresponsive nodes during crawl.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#201]
Ideally we should never come across an offline node during a crawl because the `shutdown` api sends out a `fin` packet to connected nodes which causes them to remove them from their routing tables. 

But this doesn't work perfectly. Mostly people are still not shutting down with the api which leaves their node still in other people's routing tables. Also, as the network grows, the `fin` packets may not make it to all the nodes with your node in their routing table. 

In either case the problem is each iteration of the crawl gets a list of nodes back as a response, which it then tries to query `alpha` nodes from that list. But if a node is offline, it waits for the timeout before moving on to the next iteration, which slows down the crawl. But the issue is the next iteration also returns that dead node in the response, triggering yet another attempt to contact a dead node and waiting another timeout interval. This can happen over and over until the crawl finishes. 

The obvious solution is to keep track of dead nodes found during a crawl and check each response against that dead node list, removing the dead nodes from the response before pushing the list onto the heap.

**Comment by hoffmabc** [comment]
Is this just a placeholder issue or you plan on submitting a fix?

**Comment by cpacia** [comment]
Just a placeholder. Although now that I look at it, the code does remove dead nodes before the next crawl, but it removes them by guid not ip. If someone has multiple guids for the same dead IP it will still hang on each iteration.

**Comment by cpacia** [comment]
Well I'll close this for now as it's more related to #49
