### ISSUE TITLE
IP exposed to other users 

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#202]
Exposing your local IP to other users can potentially be a security issue not just for anonymity, but for potential DoS attacks. This has been issue for Skype users for a long time and they have recently made a fix to avoid giving out your direct IP. 

Please note that using a VPN meant for this can protect you, but we should work to figure out a stronger solution out of the box.

**Comment by drwasho** [comment]
What if we had Tor-style encryption and routing of packets between OpenBazaar nodes?

**Comment by cpacia** [comment]
There's no point in build Tor from the ground up @drwasho. We couldn't possibly do it better.

**Comment by papermate** [comment]
Why not embed an I2P or Tor router and make the connections pass through that by default? It would make no visible difference for the user in terms of easiness but a huge one in terms of privacy and security.
I know Tor does not support UDP, but being OB a closed network the problem could be overcame by using OnionCat on top of it.

Just my couple of satoshis

**Comment by drwasho** [comment]
Link to #240

**Comment by drwasho** [comment]
Overlap with #164.
