### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#203]
Self explanatory

**Comment by cpacia** [comment]
@Renelvon you have in your docs that txrudp supports IPv6, did you test that on multiple nodes? If so, how did you do it. Last time I tried, I couldn't get it to work.

**Comment by Renelvon** [comment]
I haven't been able to test IPv6 at all, but I don't see why I should have to. I don't process IPs inside `txrudp`, I just copy them from one place to another. I rely on `Twisted` for IPv6 support, which is admittedly somewhat [incomplete](https://twistedmatrix.com/trac/wiki/IPv6) right now.

**Comment by drwasho** [comment]
This will be covered by upgrading to IPFS.
