### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by bitcoinbrisbane** [OpenBazaar/OpenBazaar-Server#207]
Installing requirements on Ubuntu server I get the following:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xgpuxZ/pynacl

**Comment by drwasho** [comment]
Try `pip install --upgrade pynacl`

**Comment by bitcoinbrisbane** [comment]
Thanks Washo, still same error though

On 7 Feb 2016, at 3:30 PM, Dr Washington Sanchez <notifications@github.com<mailto:notifications@github.com>> wrote:


Try pip install --upgrade pynacl

-

**Comment by drwasho** [comment]
@bitcoinbrisbane join us in our Slack group here so we can give you closer support: https://openbazaar-slackin-drwasho.herokuapp.com/
