### ISSUE TITLE
Error installing on raspbian 

### ISSUE THREAD

**Issue by papermate** [OpenBazaar/OpenBazaar-Server#217]
Hello there, I'm trying from a couple of days to install Openbazaar on a minimal Debian Jessie (Raspbian) on Raspberry pi following the instructions written [here](https://github.com/OpenBazaar/OpenBazaar-Server/wiki/Raspberry-Pi-Install-Raspbian), except that I started with a more minimal OS.

The full output is here: https://paste.debian.net/379977/

Hope you can help me, I tried by my self but could not solve it.

Thanks!

**Comment by craig131** [comment]
One error I see is "pkg-config not found", so try installing that. There may be other dependencies you are missing too.

**Comment by papermate** [comment]
I ended up installing it on a cubieboard 2 without problems (server side at least), but I'll try installing pkg-config.
Is there a complete list of dependencies?

**Comment by craig131** [comment]
I don't know, but I'd recommend using a more generic Linux install guide if you're using a "more minimal" install of Raspbian. The guide you referenced is assuming you have a specific environment already set up so it is very inflexible.

**Comment by cpacia** [comment]
We'll try to make sure we have a complete guid for this.
