### ISSUE TITLE
Failure on install: Windows 10

### ISSUE THREAD

**Issue by VivaLaPanda** [OpenBazaar/OpenBazaar-Server#219]
When I run pip install -r requirements.txt, the installation begins fine, but crashes midway through. The error is: 
```
LINK : fatal error LNK1181: cannot open input file 'libminiupnpc.a'
    error: command 'C:\\Users\\Adrian Smith\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1181
```

**Comment by VivaLaPanda** [comment]
I'm running python 2.7 on Windows 10.

**Comment by hoffmabc** [comment]
Are you using the installer or just trying the manual build?

**Comment by VivaLaPanda** [comment]
Manual, just following the instructions on https://github.com/OpenBazaar/OpenBazaar-Server/ . I didn't think there was a full Windows installer yet?

**Comment by hoffmabc** [comment]
Download the exe https://github.com/OpenBazaar/OpenBazaar-Installer/releases/tag/v1.0.1

**Comment by VivaLaPanda** [comment]
Thanks a lot! Should those be put in the readme for OpenBazaar-Installer? The readme made me think that there were no complete executables on GitHub.
