### ISSUE TITLE
Messages stored in the DHT aren't being cleared

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#230]
Brief Description: 

When I restart my node, I get all the messages that have been stored in the DHT from when I was offline (or online but the connection was an issue). When I restart again I get all these messages again. Aren't they supposed to get cleared from the DHT on receipt? 

Operating System (OS and version): Ubuntu
OpenBazaar version: source, pulled this morning
Hardware: cloud node

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Go offline
2. Send yourself messages from elsewhere so they go into the DHT
3. Come online a few times and receive all the same messages. 

Observed Behavior:

Receive the same messages each time on start up.
NB: this is only observed by adding code to MessageListenerImpl.notify 

Expected Behavior:

That messages are cleared from the DHT on receipt, so they do not trigger MessageListenerImpl.notify on restart of the node.

**Comment by cpacia** [comment]
There's more work that needs to be done with the dht. The node that sets the data is supposed to issue a store request to the nearest node without the value to increase the probability of the data persisting. 

There are two problems:

1) the ttl should be reduced when setting further away from the neighborhood. See #86

2) The delete command doesn't make it to the nodes outside the neighborhood. Which is probably why the data is still persisting after delete. 

The question is should we just not set the data at the nearest without value.

**Comment by drwasho** [comment]
Did your recent PRs close this issue @cpacia ?

**Comment by cpacia** [comment]
I made it so retrieving messages doesn't set at nearest without value.
