### ISSUE TITLE
Include Your Own Items in get_homepage_listings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#234]
Brief Description: when get_homepage_listings is called on the socket, return your own items as well as other items. Currently your own items are not in the data returned.

**Comment by cpacia** [comment]
The items that are returned are a random collection from various nodes. Even if I stick your own listings in there... if there are a lot of vendors/items you're probably not going to see it. Is there a reason why they need to show there? The point is to browse what other people have for sale. You already know what you have for sale.

**Comment by hoffmabc** [comment]
I think it would be most important just to be able to search for your own listings which I think already works doesn't it?

**Comment by drwasho** [comment]
The rationale is that folks might not think that their listings are on the network if they can't see them in the Discover tab. Admittedly, this is a guess and premature optimization, but I'd like to leave this issue open if we find we get a lot of feedback to confirm the guess.

**Comment by drwasho** [comment]
I changed my position on this issue. I don't think my concern will be a problem.
