### ISSUE TITLE
Allow -ALLOWIP access from a CIDR block or IP range

### ISSUE THREAD

**Issue by bdunbar** [OpenBazaar/OpenBazaar-Server#237]
Brief Description: Is it possible to change startup parameter -a from 'an' IP to a CIDR block.

Operating System (OS and version): All
OpenBazaar version: 0.9
Hardware: n/a

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

A gedankenexperiment that illustrates a problem I could have running OB stores on my own servers.

Steps to reproduce:
1. Shell in to my remote host.
2. Start OpenBazaar python openbazaard.py start -a 68.52.199.70 --testnet
3. Realize that the address where I run my client has changed.
4. Get my new, current IP: 68.52.199.74.  Thanks, Comcast!
5. Start OpenBazaar python openbazaard.py start -a 68.52.199.74 --testnet
6. Login with Client and we're good to go.

Expected Behavior: 
1. Connect to my provider's VPN.
1a. VPN assigns me an address '172.27.227.123'
3. Shell in to host.
4. Start OpenBazaar like so: python openbazaard.py start -a 172.31.0.0/16 --testnet
5. Login with my client to the 172.xxx address assigned to my remote host.
6. Provide my password and I'm in.

Additional info (links, images, etc go here):

I'm groping for a secure, and convenient, method of hosting OB servers.

One headache is provisioning an OB server with 'a' remote IP.  These change, over time.  Sally Shopowner is going to login from home, do some edits, then later want to login from Starbucks. This is going to get complicated, for her, and annoying, in a big hurry.

It occurs to me that if I, as a hosting provider,

1. Set the OB server with a user/password.
2. Tell the OB server to expect traffic only from a private CIDR block that is my VPN.
3. Have my customers login to a VPN.

I can cut down on the management burden, a lot.

Granted, a VPN still isn't _great_, so I'm still working on this.

Thoughts?

**Comment by cpacia** [comment]
Probably would need to think of another way to do it. Right now I'm just overrieding the `buildProtocol` method in twisted.web.server.Site and it only passes in a string IPv4 address and port.

**Comment by bdunbar** [comment]
Then, another way it is.  Thanks, cpacia.
