### ISSUE TITLE
Add vendor/moderator to get_following and get_followers

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#242]
Brief Description: 

Add "vendor: true/false" and "moderator: true/false"  to the data returned from get_followers and get_following.

This is needed for the follower and following tab filters on the user page.

**Comment by cpacia** [comment]
This data does not exist in the following data (and also can change frequently as well).

**Comment by drwasho** [comment]
@jjeffryes given some of the scaling problems with the followers list, I think we may have to close this.

**Comment by jjeffryes** [comment]
It's not a critical issue, we can close it.
