### ISSUE TITLE
Notifications should include the user avatar instead of the listing image. 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Server#245]
It's a bit confusing currently. Some notifications display the listing image and others display the user avatar. I'd rather just display the user avatar in all cases since the user is really the one performing the action and generating the notification. 

<img width="446" alt="screenshot 2016-02-29 10 59 44" src="https://cloud.githubusercontent.com/assets/13066886/13401900/8f637f62-ded3-11e5-9576-06f7f911e2e7.png">

**Comment by cpacia** [comment]
This issue you will have is sometimes (like in the case of a new sale) the seller wont have the buyer's avatar and he likely signed offline by the time you click the notifications.

**Comment by morebrownies** [comment]
Ok, I'll work around it for now.
