### ISSUE TITLE
The buyer shouldn't receive a payment received notification

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Server#246]
Payment received notifications should only be sent to the vendor. They're currently displaying to the buyer. 

<img width="446" alt="screenshot 2016-02-29 10 59 44" src="https://cloud.githubusercontent.com/assets/13066886/13402157/a5d6cb7c-ded4-11e5-8d5b-50d780385986.png">

**Comment by cpacia** [comment]
This you have to handle on the client side. The notification is used by the client to tell when the bitcoin transaction is detected. So I can't not send it.

**Comment by morebrownies** [comment]
Chris what is the difference between the "payment received" notification and "new order" notification? They seem very similar... Do we need both?

**Comment by cpacia** [comment]
new order goes to the seller. payment received is so the client knows when the bitcoin transaction goes through.
