### ISSUE TITLE
Messages are getting stuck in the DHT and not deleted

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#252]
I was speaking to a user and I've had a message of his repeat randomly. He also had one of mine repeat randomly. He didn't go offline during our conversation. I know what's happening so I can ignore these duplicates if I have the sense at the time to spot them, but it's very confusing for new users when they see me repeat 'No Problem.' randomly and out of context.

Is there anything that can be done about this?

**Comment by dsmurrell** [comment]
Suddenly, another 4 messages from the DHT: 
![screen shot 2016-03-02 at 17 11 31](https://cloud.githubusercontent.com/assets/4035854/13468340/0c118d52-e09a-11e5-8cb5-38504987825e.png)

**Comment by cpacia** [comment]
I have it check for duplicate messages before saving to the db, but it doesn't stop it from pushing it to the UI. I'd have to think about how to do that.

**Comment by dsmurrell** [comment]
I'm also sending the messages somewhere. What is the method you use to
check for duplicates? Do you check the entire conversation history or only
up until a certain time in the past?

**Comment by cpacia** [comment]
It checks if the message is already in the db when trying to save it.
