### ISSUE TITLE
Don't allow values of u'\xa0'

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#254]
Due to shenanigans with the Medium-editor library, it was possible to enter a single space for the description in a profile or listing. This causes that profile or listing to be unreadable from the server.

This will be prevented in the client, but should also be prevented on the server, either by returning an error when values containing a single space are submitted, or by stripping them (replacing them with blank values).

**Comment by cpacia** [comment]
Can you try doing this on master and see if it's still an issue? I believe I've fixed it.

**Comment by jjeffryes** [comment]
Will do.

**Comment by jjeffryes** [comment]
It appears to be a problem with non-breaking spaces also. 

The medium editor puts in a non-breaking space if the field is edited then erased, sending <p>&nbsp;</p> to POST profile makes the profile unreadable.

**Comment by jjeffryes** [comment]
That should be "paragraph tag non-breaking space paragraph tag"

`<p>&nbsp;</p>`

**Comment by cpacia** [comment]
This is on master you're still seeing this?

**Comment by jjeffryes** [comment]
Yes.
