### ISSUE TITLE
OpenBazaar page not accessible, even though it appears in lists of people I follow

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Server#256]
This problem has existed since I started testing OpenBazaar several months ago. In summary, I have created a page (lunokhod: 34786ba7b8f3de6f63a3e0bb4e1cf327c9a991bb), and have favorited several people (such as Vintage Fashion, Chris Pacia, @sampatt). I am running my server continuously, but it is located at a university where it is behind some kind of firewall that is beyond my control (this firewall, however, does not stop me from running a bitcoin node, i2p, and other p2p software).

Now, if I run an OpenBazaar node from my personal internet connection at home, I notice that my page is not accessible. However, when I look at the above favorited pages, I note that my account is listed, along with its short description. So, it appears that I can see that outside world, I can send information (like favoriting) to the outside world, but the outside world can't see me.

For info, when I start the server, I get the following output

~~~~
OpenBazaar Server v0.1 starting...
Exception : No UPnP device discovered
2016-03-02 09:47:21+0100 [OpenBazaard] [INFO] Finding NAT Type...
2016-03-02 09:47:29+0100 [OpenBazaard] [INFO] Symmetric NAT on xxx.xxx.xxx.xxx:13318
2016-03-02 09:47:29+0100 [OpenBazaard] [INFO] Startup took 12.38 seconds
2016-03-02 09:47:30+0100 [Server] [INFO] bootstrapping with 10 addresses, finding neighbors...
2016-03-02 09:47:30+0100 [ConnHandler] [INFO] connected to 104.131.6.245:28467
~~~~

Also, I note that I am downloading the source directly from github, and that I am using Mac OSX.

**Comment by cpacia** [comment]
Symmetric NATs are hard to work with. We have code to relay packet through other nodes and as far as I know it works, but it might have problems in some situations.

**Comment by lunokhod** [comment]
Thanks for the response. Unfortunately, it appears that your symmetric NAT approach is not working. Just contact me if you would like me to test any future bug fixes.
