### ISSUE TITLE
Transferring the "labeled" item BTC price get ignored

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#257]
Copied from  https://github.com/OpenBazaar/OpenBazaar-Client/issues/941 by @ac225519

If one pays (accidentally, inexperienced with BTC) the "labeled" BTC price instead of the ​exact​ amount in the "pay" dialogue, the payment get complete ignored by OpenBazaar.

Operating System (OS and version): All
OpenBazaar version: 1.0.6 git ID:5dbca08 downloaded 2016-Mar-02 02:27:02 U
Hardware: All

Reproducible: Always

Steps to reproduce:
1. Click on "BUY NOW" on a item.
2. Transfer the labeled item price to the wallet address listed in the payment dialogue.

Observed Behaviour:
The only little too short payment get complete ignored by OpenBazaar.

Expected Behaviour:
"A payment of xxx BTC has been received for this transaction. yyy BTC are missing"

Would be what I would expect.

**Comment by drwasho** [comment]
With the Bitcoin price API work done on the server, I think this was fixed.
