### ISSUE TITLE
Add id based 'before' argument to the get_notifications api

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/OpenBazaar-Server#266]
Please add in a _before_ argument to the get_notifications API, so that notifications can be fetched in batches. Please make the argument _id_ rather than _index_ based, because the list is constantly changing making the index a moving target.

So, calling the API with limit: 10, before: 9999, would return the ten most recent notifications that came before the notification with id '9999'. Ideally, the result set would not include #9999.

**Comment by cpacia** [comment]
This is done
