### ISSUE TITLE
"Unable to connect to your server" suddenly appears on OS X El Capitan Server

### ISSUE THREAD

**Issue by i1o** [OpenBazaar/OpenBazaar-Server#267]
Brief Description: 

Operating System (OS and version): OS X El Capitan
OpenBazaar version: 1.0.6/7
Hardware: Macbook Air mid 2012

Reproducible (Couldn't Reproduce): I set up OpenBazaar account, made few customisations and then my client suddenly showed me login-to-server page. Trying to reconnect fails every time. Updating from 1.0.6 to 1.0.7 did't help.

I can't see what's going wrong. Has anybody experienced the same issue? 

Renaming/deleting ~/Library/Application Support/OpenBazaar folder helps to start the on-boarding process from scratch. But what if I have to save my account ect.?

**Comment by drwasho** [comment]
Please join slack.openbazaar.org for closer real-time support if this is still an issue.

**Comment by tmm360** [comment]
I still have this issue, I'm using El Capitan with Openbazaar 1.1.4
