### ISSUE TITLE
Order shipped by vendor does not update for buyer until buyer restarts node.

### ISSUE THREAD

**Issue by insanity54** [OpenBazaar/OpenBazaar-Server#269]
I was testing the buying process with help from @SamPatt. Sam created an item for me to buy, which I did. Thru slack, Sam told me he marked the item as shipped. I waited on my end for a notification that the item had been shipped. 19 minutes passed, but in my purchase history, the item did not show as shipped on my end.

"Ready to process (Paid in full)"

Again thru slack, I asked Sam if I should wait some more, but he said it should not take this long, and suggested I restart my node. I did that, after which I saw the item status in my purchase history change to "Confirmed/Shipped"

OSX 10.9.5.
OB 1.0.7.
2011 Mac Mini

I was able to reproduce the problem. I purchased the item again, and let Sam know through slack. He shipped the item and noted that he received the money. I waited for another 19 minutes and did not see the item status change to shipped. Upon restarting OB, the item immediately changed to "Confirmed/Shipped".

**Comment by SamPatt** [comment]
Thanks for the report @insanity54 

On my end when I went to confirm the sale, after hitting "save" it didn't change for several minutes but eventually did register.

@cpacia I assume this is a DHT issue.

**Comment by insanity54** [comment]
BTW, In OB advanced settings, firewall shows "Restricted"

**Comment by cpacia** [comment]
Yeah so the issue is Sam's node was unable to make a connection to the buyer and stuck the message in the dht.

You actually don't need to restart your node to get the message but it only checks the dht once per hour. If you waited an hour it would have shown up. 

As to why Sam's node didn't connect, I don't know. It could be a bug, NAT issues or slow internet. Hard to say without debugging it.

**Comment by insanity54** [comment]
Makes sense. And in a real-world sale this wouldn't even matter to me the buyer, since I wouldn't be expecting the seller to ship in under an hour, or even see within an hour if the seller had shipped.

**Comment by drwasho** [comment]
@cpacia can create an api to manually check the DHT?
