### ISSUE TITLE
Enable Buyer ratings for disputes that they win

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#271]
If the Vendor tried to screw over the Buyer, and the Moderator was required to settle the dispute, then the Buyer should have the opportunity to leave a negative rating. 

Client link: https://github.com/OpenBazaar/OpenBazaar-Client/issues/860

**Comment by jjeffryes** [comment]
Currently, when I tried calling complete_order on an order with a finalized dispute, this was the response from the server:

web.Server Traceback (most recent call last):
exceptions.KeyError: 'vendor_order_confirmation'
C:\python27\lib\site-packages\twisted\web\server.py:184 in process
183        try:
184            resrc = self.site.getResourceFor(self)
185            if resource._IEncodingResource.providedBy(resrc):
C:\python27\lib\site-packages\twisted\web\server.py:706 in getResourceFor
705        request.sitepath = copy.copy(request.prepath)
706        return resource.getChildForRequest(self.resource, request)
707
C:\python27\lib\site-packages\twisted\web\resource.py:98 in getChildForRequest
97        request.prepath.append(pathElement)
98        resource = resource.getChildWithDefault(pathElement, request)
99    return resource
C:\python27\lib\site-packages\twisted\web\resource.py:201 in getChildWithDefault
200            return self.children[path]
201        return self.getChild(path, request)
202
C:\python27\lib\site-packages\txrestapi\resource.py:63 in getChild
62            else:
63                return maybeResource(callback)(request, **args)
64        else:
C:\python27\lib\site-packages\txrestapi\resource.py:19 in inner
18    def inner(*args, **kwargs):
19        result = f(*args, **kwargs)
20        if not isinstance(result, Resource):
C:\Users\J\ob\OpenBazaar-Server\api\restapi.py:57 in _authenticate
56            else:
57                func(self, request)
58                return server.NOT_DONE_YET
C:\Users\J\ob\OpenBazaar-Server\api\restapi.py:809 in complete_order
808                      if "customer_service" in request.args else None,
809                      review=request.args["review"][0].decode("utf8") if "review" in request.args else "")
810        guid = c.contract["vendor_offer"]["listing"]["id"]["guid"]
C:\Users\J\ob\OpenBazaar-Server\market\contracts.py:569 in add_receipt
568        }
569        order_id = self.contract["vendor_order_confirmation"]["invoice"]["ref_hash"]
570        if None not in (feedback, quality, description, delivery_time, customer_service):
exceptions.KeyError: 'vendor_order_confirmation'
