### ISSUE TITLE
Moderation Fee is not saved

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#273]
Brief Description: when moderator: true and moderation_fee: any number is sent to POST profile, the moderation_fee is ignored. 

Reproducible: always

Steps to reproduce:
1. in either the user page or the settings page, change your moderation fee
2. save
3. refresh the page. 

Observed Behavior: Setting the fee may work the first time a user becomes a moderator. After that, new values are ignored, and the original value is returned from GET profile

Expected Behavior: the new value should be saved

https://github.com/OpenBazaar/OpenBazaar-Client/issues/989#issuecomment-192928931

**Comment by saltduck** [comment]
I cannot reproduce this case. The behavior is as expected.

OS: Ubuntu 15.04
OB: master

**Comment by hoffmabc** [comment]
Is this still only when setting to 0%?

**Comment by jjeffryes** [comment]
No, it happened to me when my fee was set to 1%.

**Comment by cpacia** [comment]
I'm not able to set to zero percent but every other percentage seems to work fine.

**Comment by saltduck** [comment]
@cpacia +1

**Comment by drwasho** [comment]
Still a problem @jjeffryes ?

**Comment by jjeffryes** [comment]
This is no longer an issue.
