### ISSUE TITLE
Fails to start, protobuf error

### ISSUE THREAD

**Issue by noflag** [OpenBazaar/OpenBazaar-Server#28]
Using Mint, fully updated. Protobuf from both apt and pip. Error:

python openbazaard.py 
Traceback (most recent call last):
  File "openbazaard.py", line 13, in <module>
    from db.datastore import create_database
  File "/home/eric/Apps/OpenBazaar-Server/db/datastore.py", line 5, in <module>
    from protos.objects import Listings, Followers, Following
  File "/home/eric/Apps/OpenBazaar-Server/protos/objects.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

**Comment by hoffmabc** [comment]
I believe it was a protobuf issue.

Try

```
sudo apt-get remove python-protobuf
```

**Comment by cpacia** [comment]
Yeah Mint ships with an old version of protobuf. If you remove it before installing the new one, it should be fine. I was able to get it working on mint by doing that.

**Comment by jojva** [comment]
I ran into the same problem, it would be nice if there was an indication somewhere, like in README.
