### ISSUE TITLE
Create Bitcoin Conversion API

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#285]
Currently the server and client use two different methods to calculate the price of fiat currencies in bitcoin. This results in the price for products being different in most parts of the client vs the price returned by purchase_contract.

We should use a single method on the server to keep the prices in sync. 

The API should work something like this:

**Inputs:** currency code (3 character ISO code)

**Outputs:** current value of 1 bitcoin in the passed in currency, an array of all the 3 character currency codes returned by at least one of the 3rd party APIs

When called, the API would do the following:

1. call multiple 3rd party APIs to retrieve a list of available currencies and the current value of 1 BTC in each currency

2. for each currency that has at least one value, average all the values (ie: if all 4 APIs return a value for USD, average the 4 values. If only one returns a value for AUD, use that value). 

3. Store the results, and only fetch new prices if more than 15 minutes has elapsed

4. Return the average price of 1 BTC in the passed in fiat currency, and return an array of 3 digit currency codes, so the client knows which currencies can be used (this prevents the user from setting the client to use a currency we can't retrieve a price for). 

The output could be similar to this:

{
btcAve: 561.64017625,
currencyCodes: [ 
0: "USD",
1: "ISK",
2: "HKD",
3: "TWD",
4: "CHF",
5: "EUR",
6: "DKK",
7: "CLP",
8: "CAD",
9: "CNY",
10: "THB",
11: "AUD",
12: "SGD",
13: "KRW",
14: "JPY",
15: "PLN",
16: "GBP",
17: "SEK",
18: "NZD",
19: "BRL",
20: "RUB",
21: "KWD",
22: "MXN",
23: "MYR",
24: "NOK",
25: "PHP",
26: "VUV",
27: "ZAR",
28: "IDR",
29: "ILS",
30: "INR",
31: "RON",
32: "XRP",
33: "LTC",
34: "ARS",
35: "CZK",
36: "NMC",
]
}

**Comment by drwasho** [comment]
How do you want to tag this? Important enough for a mainnet release?

**Comment by jjeffryes** [comment]
This has been completed.
