### ISSUE TITLE
Republish listings after keywords expire from DHT

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#286]
This prevents a collapse of search capabilities in the network because the keywords have expired. The listings should auto-republish considering that the node is online in the first place.

**Comment by cpacia** [comment]
this was done

**Comment by drwasho** [comment]
Well my Vintage Fashion node has been online with the same listings for ages and I had to republish them manually so they could be detected in search.

**Comment by cpacia** [comment]
It doesn't republish for like 5 days

**Comment by drwasho** [comment]
Ok... couple of questions:
1. 5 days 'on-time', or 5 days since the listing was published?
2. When do the keywords expire?
3. Even with the current settings, something is not working considering the number of people reporting that their contracts can't be search and I had to manually republish to restore search capability for my listings.

**Comment by cpacia** [comment]
1. 5 days after it was published.
2. 1 week. 
3. Some of that could just be that dht searches are very slow and people aren't waiting. It's hard to debug that.

**Comment by drwasho** [comment]
On the last point, it's not that we're being impatient. We left the search running for a good 5-10 minutes. Then after we republished, instantly returned search results.
