### ISSUE TITLE
Feature request: Send an email through local sendmail for each notification

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Server#289]
I suggested this [on Reddit](https://www.reddit.com/r/OpenBazaar/comments/49stjy/feature_request_send_an_email_for_each/), and it seemed to get some positive comments.

----

I realize this might not be straight forward, since there is no central server to send out emails, but perhaps a call to the user's local sendmail can be triggered, if OpenBazaar is running on a Linux machine? Or at least add an option to enable or disable this.

I think it would be nice for people who are running the OB server headlessly and maybe remotely, that they can enable emails to be instantly notified of sales, questions from buyers, money received, updates on disputes, etc. Maybe even PGP encrypted emails.

**Comment by drwasho** [comment]
We're going to use this issue to track the email feature @hoffmabc 

## Requirements

**As a user, I need to get an email when...**
- [ ] Someone follows you (once per node)
- [ ] Dispute opened
- [ ] Dispute resolved
- [ ] Chat message (once per node per day)
- [ ] Chat message in an order (once per node per day)

**As a Vendor, I need to get an email when...**
- [ ] I receive a funded order
- [ ] I receive funds (direct or escrow)
- [ ] I receive a rating received

**As a Buyer, I need to get an email when...**
- [ ] The order is confirmed/shipped
- [ ] An order refunded

**Comment by drwasho** [comment]
We also need email templates for each of these email notifications. @SamPatt this might be a good one for you.

**Comment by SamPatt** [comment]
Thanks @drwasho I'll look at this.

Minor point: The "Dispute resolved" message should probably be different based on if they won or lost a dispute, since one requires action (accept payout) and the other doesn't.

**Comment by jjeffryes** [comment]
This was completed.
