### ISSUE TITLE
Ban score

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#3]
We will need to draft up some metrics for what will constitute a ban score and ban peers when they go over the threshold. 

Feedback on what metrics should be included is welcome.

**Comment by llamaha** [comment]
How about an upvote/downvote system?  Then ban depending on percentage once a certain amount of votes have been received.  Have it kick in when people click a 'report' button.

if ((up + down) > 10) && (up / down) < 0 ....

Following this have comments about the peer (in question) reviewed by members of the community in return for rewards points.  This way you are using a jury to decide whether or not the peer should have their account restored.

**Comment by cpacia** [comment]
Well I'm not really referring to banning nodes from the network, just dropping nodes that are dos-ing your node. The ban score is just a way to try to measure that.

**Comment by gubatron** [comment]
"account"?

**Comment by cpacia** [comment]
This is going to be a large undertaking so it's best to get the ball rolling sooner rather than later.

Obviously malformated messages should increase the ban score. So should messages with incorrect network parameters (testnet/mainnet). But we probably need to handle each individual message type differently to prevent DoS. The following are some thoughts on what would constitute correct use/misuse of each message type.

**PING**
There's never really any reason to send a ping more than once every 30 seconds.

**STUN**
This isn't used at the moment and we shouldn't see this message coming from other nodes.

**HOLE_PUNCH**
This is hard to say how frequently we should see this message. If a node is trying to send a bunch of STORE requests that fail to get through, it may trigger a flurry of HOLE_PUNCH messages. However, we should not see this flurry of messages happening too frequently since once the port is mapped, HOLE_PUNCH shouldn't be needed again anytime soon. 

**STORE**
We can't really limit store requests because nodes don't just issue store requests for their own data, but also data they received from others in an attempt to keep it alive. The best we can do here is implement #5.

**DELETE**
Invalid delete messages (invalid signature, data doesn't exist, etc) should increase the ban score. Other than that it's hard to say how frequently delete messages should be allowed because they may come in flurries if a user deletes a contract, or deletes downloaded messages from the dht. We should, however, prevent someone from rapidly issuing STORE/DELETE commands.

**NOTIFY**
We should never receive a NOTIFY message from a node we are not following. The should be banned if we do. Additionally, notifications should probably be rate limited to prevent people from spamming their followers. 

**MESSAGE**
These are messages sent to other nodes. There may be a fair amount of back and forth communication between people but we should probably still rate limit it to a reasonable amount of bytes/minute.

**FOLLOW**
Should never receive a FOLLOW request from a node that is already following us. 

**UNFOLLOW**
Should never receive an UNFOLLOW request from a node that isn't following us. We also should prevent nodes from issues rapid FOLLOW/UNFOLLOW requests.

**ORDER**
Order messages can probably be rate limited as users wont be expected to rapidly place orders with vendors. 


**ORDER_CONFIRMATION**
We should never receive an order confirmation message if we don't have any outstanding order that is waiting for one.

**COMPLETE_ORDER**
We should never receive this message if we don't have any outstanding sales that is waiting for one. 
	
**FIND_NODE**
With the exception of a few places (such as republishing dht data or downloading messages at startup), this message is mostly triggered by user interaction. As such we shouldn't expect rapid flurries of find node messages and it can probably be rate limited.

**FIND_VALUE**
Same as FIND_NODE

**GET_CONTRACT**
Contracts are cached by nodes so we really shouldn't see this message called more than once per contract hash. If it's called more than once per contract hash within some time frame, we should increase the ban score.

**GET_IMAGE**
Same as GET_CONTRACT. No reason to call repeatedly.

**GET_PROFILE**	
**GET_LISTINGS**
**GET_USER_METADATA**
**GET_CONTRACT_METADATA**
**GET_FOLLOWING**
**GET_FOLLOWERS**
All of the above are triggered by user interaction and can probably be rate limited.

**BAD_REQUEST**
**NOT_FOUND**
**CALM_DOWN**
**UNKNOWN_ERROR**
Should not allow our node to be bombarded with error messages.

**Comment by hoffmabc** [comment]
This is a great list. We should talk through this very soon.

**Comment by ABISprotocol** [comment]
I understand what you are trying to do, but what will happen is that a large number of users will find themselves hitting bans without even understanding why, because you have developed an already large list of things that trigger ban scores and people aren't going to be able to keep track of all these rules in these routine behavior and interaction with OB.

Please try and remember you are trying to create an alternative to Amazon and eBay, not a clone.

**Comment by hoffmabc** [comment]
It is desired to not let users understand that their attacks are successful or else they may adjust their strategies and nullify this mitigation.

**Comment by ABISprotocol** [comment]
Counterpoint to that is to not get so crazy with it that you end up alienating ordinary users who are actually doing nothing.

**Comment by hoffmabc** [comment]
It should never punish normal users or common scenarios. Agreed.

**Comment by drwasho** [comment]
@cpacia do you still want to keep this issue open?

**Comment by drwasho** [comment]
Being addressed in PR #319
