### ISSUE TITLE
get_vendors returns duplicates

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#302]
When get_vendors is called, it sometimes returns up to 4 identical results for each vendor.

For example

{"request":{"api":"v1","id":"mhzyo4asbgeyu8fr","command":"get_vendors"}}

Returned

{
    "vendor": {
        "handle": "", 
        "name": "Bit Garden", 
        "nsfw": false, 
        "short_description": "Grow something unusual, go on, I dare you!", 
        "avatar_hash": "039a3028870e150db9d02c8833bfab699003d54e", 
        "guid": "5b704e926328719e60328ebee174408669956e69"
    }, 
    "id": "mhzyo4asbgeyu8fr"
}

{
    "vendor": {
        "handle": "", 
        "name": "Bit Garden", 
        "nsfw": false, 
        "short_description": "Grow something unusual, go on, I dare you!", 
        "avatar_hash": "039a3028870e150db9d02c8833bfab699003d54e", 
        "guid": "5b704e926328719e60328ebee174408669956e69"
    }, 
    "id": "mhzyo4asbgeyu8fr"
}

{
    "vendor": {
        "handle": "", 
        "name": "Bit Garden", 
        "nsfw": false, 
        "short_description": "Grow something unusual, go on, I dare you!", 
        "avatar_hash": "039a3028870e150db9d02c8833bfab699003d54e", 
        "guid": "5b704e926328719e60328ebee174408669956e69"
    }, 
    "id": "mhzyo4asbgeyu8fr"
}

{
    "vendor": {
        "handle": "", 
        "name": "Bit Garden", 
        "nsfw": false, 
        "short_description": "Grow something unusual, go on, I dare you!", 
        "avatar_hash": "039a3028870e150db9d02c8833bfab699003d54e", 
        "guid": "5b704e926328719e60328ebee174408669956e69"
    }, 
    "id": "mhzyo4asbgeyu8fr"
}

See also client issue https://github.com/OpenBazaar/OpenBazaar-Client/issues/1018

**Comment by drwasho** [comment]
Is this still a problem @jjeffryes ?

**Comment by jjeffryes** [comment]
I'm not sure. I haven't seen it in a while, but I haven't been testing for it either.

**Comment by drwasho** [comment]
I haven't seen it for ages either. Gonna close it.
