### ISSUE TITLE
pip -r fails on autobahn==0.10.5-2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by Joaz** [OpenBazaar/OpenBazaar-Server#31]
On Ubuntu 14.04 I had to change the autobahn version to 
autobahn==0.10.5.post2

as version 0.10.5-2 does not "exist"

Can this maybe use a >= for the version number?

**Comment by hoffmabc** [comment]
If you update this to the latest autobahn==0.10.9 do you get the issue?

**Comment by Joaz** [comment]
autobahn==0.10.9 works fine.

**Comment by Joaz** [comment]
this has been fixed.
