### ISSUE TITLE
Add option to only query followers during get_homepage_listings websocket query.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#311]
The `get_homepage_listings` websocket query in ws.py currently returns listings from random vendors. We want to change it to allow the client to set a flag when making the query telling it to only return results from nodes we follow. 

The `get_homepage_listings` function should then use the list of nodes we follow rather than standard vendor list.

**Comment by ddustin** [comment]
https://github.com/OpenBazaar/OpenBazaar-Server/pull/314
