### ISSUE TITLE
Too aggressive image fetching

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#348]
[This line of code](https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/market/network.py#L135) (and the following) causes failures in image fetching:

    for image_hash in contract["vendor_offer"]["listing"]["item"]["image_hashes"]:
        self.get_image(node_to_ask, unhexlify(image_hash))

If the listing has many images then doing `get_image` on all images at the same time is too aggressive and results in failures.

**Comment by drwasho** [comment]
This call is to get a contract with all the images attached to it... That's the entire point. I forget the exact maximum number of images a contract can have, but it's safely no more than 15... And if the user wants to access the full contract with images, this is the call they'd make.

**Comment by JustinDrake** [comment]
@drwasho I've tested it. 15 concurrent image fetches often results in failed fetches. The obvious solution is throttling.
