### ISSUE TITLE
BTC prices decline without user/merchant intervention.

### ISSUE THREAD

**Issue by nukebloodaxe** [OpenBazaar/OpenBazaar-Server#355]
Brief Description: I've observed the price of a test item decrease from 0.0030 BTC to 0.002940891089108911 with no interaction on my part.

Operating System (OS and version): Windows 10 client, Linux server (Ubuntu 15.10)
OpenBazaar version: Git release 1.1.2 pulled 15/04/2016 NZ time.
Hardware: Minimal Digital Ocean Droplet

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Was reproducable, then wasn't, but it appears to have affected other listings.  Noticed fault after a follower joined my page, at that time fault could be reproduced, from slack:

```
Reproducible bug.  Clicked notifications, went back to store page, listing is 0.0029 again.  However, it stayed this time, editing the entry shows a price of: 0.002940891089108911

[10:28] 
After edit the 0.0030 is sticking properly... odd.  Might be time related.
```

Observed Behavior:  Reduction of prices in stores

Expected Behavior: No reduction of prices in stores.

Additional info (links, images, etc go here):
Original listing: ob://@nuke_bloodaxe/listing/8e0db488113a5c28b0fbc3eddd8915cda6e1211e
Another test listing which I remember being 100BTC, but is now 99.0099 BTC: ob://@MichaelHoffmann/listing/60522fb4dce8f6813bd5d1d89ce01fa759c24a5d ; I could be wrong, but I think it's unlikely.

**Comment by jjeffryes** [comment]
This was a floating point issue on the client, and has been fixed in Master. We'll be releasing an update soon that includes this fix.
