### ISSUE TITLE
Bitcoin client

### ISSUE THREAD

**Issue by Stemby** [OpenBazaar/OpenBazaar-Server#359]
Please integrate a complete Bitcoin client (with a full wallet), in order to avoid 2 bitcoin transactions on the blockchain (with 2 fees) for every OB transaction.

See also [this](https://www.reddit.com/r/OpenBazaar/comments/4ef7s1/bitcoin_addresses/) discussion on Reddit.

Thanks!

**Comment by drwasho** [comment]
Thanks for the suggestion. Some points: 

1. A full Bitcoin node is never gonna happen. It is antithetical to the goal of creating a mass consumer app. 
2. A Bitcoin wallet is on our roadmap. 

The two Bitcoin transactions you may be referring to that take place in a direct transaction facilitate Vendors to make easy refunds before they have shipped. Until we have a wallet in application, this two step process helps more than it hurts.
