### ISSUE TITLE
[Idea] "Shared economy" support

### ISSUE THREAD

**Issue by izqui** [OpenBazaar/OpenBazaar-Server#36]
It really bugs me that a sindicate from bus companies in Spain can take down Blablacar in the same way that they did with Uber: [Article in Spanish](http://www.elconfidencial.com/tecnologia/2015-10-01/blablacar-ante-el-juez-estos-son-sus-argumentos-para-no-cerrar-en-espana_1043143/)

Have you thought about making open bazaar support the typical sharing economy scenarios:
```
Advertisement -> Client request  -> Service acceptance -> Service gets done -> Rating
                [                           Chatting                          ]
```
It would be really cool to have a P2P network for the sharing economy

**Comment by ericfont** [comment]
I'm new to OpenBazaar.  But my basic understanding leads me to think that the OpenBazaar-Server in no way precludes sharing economy scenarios.  The server simply operates at the abstract level of identities, contracts, and ratings.  So the contract would simply be the temporary use of whatever is being shared.  

I think maybe what you are looking for is someone to develop frontend specific for the type of thing that is being shared, which would interface with the OpenBazaar-Server.  I also look forward to people developing such frontends.

Can you (or anyone else knowledgeable enough) identify something specific to the server protocol that would prohibit sharing economy scenarios?

**Comment by gubatron** [comment]
I think this is @drwasho's turf. Perhaps he's already wrote something about Sharing-economy + smart contracts.

Thinking about it more closely I bet new protocol dynamics would have to be designed.

Say you're going to do a P2P-Uber competitor, you somehow need to round up a list of near by Service Providers that would be "closest" to you, in the case of a service like Uber where geography is so important.

There could also be similar scenarios where distance wouldn't matter, just availability, say you wanted to have some Text Translated from Language A to Language B, you'd just need to be able to find a list of available translators online to solve your problem. (just thinking how to generalize)

I suppose that if you think about it, this is just a search problem, where the providers of the service would subscribe to some sort of common context, in the case of p2p-rides, it'd be "ride service openbazaar providers in a radius of X miles around point A willing to go to point B"

If openbazaar could perform such a search on the network, search results provided would include the information of the stores that would match the request, along with their current GPS location and movement vector.

So I guess that would be your answer, the search algorithm would have to be coded.

**Comment by gubatron** [comment]
DHT ftw.

**Comment by drwasho** [comment]
> I'm new to OpenBazaar. But my basic understanding leads me to think that the OpenBazaar-Server in no way precludes sharing economy scenarios. The server simply operates at the abstract level of identities, contracts, and ratings. So the contract would simply be the temporary use of whatever is being shared.

Spot on.

**Comment by drwasho** [comment]
I imagine you could design it in the following way:

1. Assume that there is an OpenBazaar server you can remote into **or** a public server you have access to.
2. Place an _invitation to tender_ (ITT) (it's formatted like a Ricardian contract, but it isn't a contract). It specifies what you what, when you want it, where you want it, and how much you're willing to pay for it. The tender will conform to some standard spec for ride-sharing that would be developed (hand-waving).
3. Drivers would bid on your ITT and send you tenders for that on-demand service. You would then rank/sort the tenders according to reputation, geography, price etc
4. Select one and place the order.

All of this may be executed through a multi-purpose OpenBazaar app or a OpenBazaar RideShare app... either way, it using the contract platform and the server APIs.

**Comment by cpacia** [comment]
Can be discussed more in slack
