### ISSUE TITLE
Show what Type A Listing Is (physical, digital, service)

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#371]
## Overview

In Discover, listings will be discernible by type: physical good, digital content, or services.

## Requirements

- [ ] Show indication of what type each listing is (physical, digital, service) in the Discover page

@cpacia to add `type` to the `get_homepage_listings` websocket call
@morebrownies to design how this will look
@jjeffryes to wire it up on the front-end

**Comment by jjeffryes** [comment]
This was completed.
