### ISSUE TITLE
Optimize Followers List Loading

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#373]
## Overview

Scaling optimization for the way the followers list loads.

## Requirements
- [ ] `get_followers` should be modified to accept a limit parameter. It should return that number of followers, or 20 if the limit parameter is not sent. **(1)**
- [ ] `get_following` should be modified to accept a limit parameter. It should return that number of followed, or 20 if the limit parameter is not sent. **(2)**
- [ ] `userPageVw.js` should be modified to call `get_followers` and `get_following` when the user scrolls to a position near the bottom of the currently loaded list. The spinner should be shown when the list is loading. **(3)**

**Comment by jjeffryes** [comment]
This was completed.
