### ISSUE TITLE
protobuf3 issue for distro packaging

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/OpenBazaar-Server#379]
# Issue:

I want to highlight that the use of protobuf3 beta 2 library it's not contemplated in common distros cause of beta quality of the library. Instead protobuf 2.x is used. 
The python2-protobuf3 library could not coexists with python2-protobuf one cause of API consistent changes and because the replacement should force the recompilation of many other software.
# Proposal:

So my proposal is to do a conditional import. if google.protobuf is not found than use google.protobuf3 module.
It's a reasonable solution?
For now I resolved using a sed expression and creating a package that realizes this coexistence until 3.x api will be stable
# OS used:

Arch Linux
# Installation:

system-wide (standalone version runs without issues)

**Comment by M0Rf30** [comment]
Solved with protobuf3 in official Arch Linux repo

**Comment by hoffmabc** [comment]
@M0Rf30 is this solvable on our end in any way?

**Comment by M0Rf30** [comment]
Of course, I've managed it replacing using:

find . -type f -exec sed -i 's/google.protobuf/google.protobuf3/g' {} +   
 find . -type f -name "*.proto" -exec sed -i 's/protoc/protobuf3-protoc/g' {} +  

for txrudp openbazaard and protobuf. Another solution is building the standalone server with pyinstaller. In AUR I packaged openbazaard and openbazaard standalone. They work flawless

**Comment by M0Rf30** [comment]
Every change is also tracked in my PKGBUILD repo on github
