### ISSUE TITLE
get_followers returns an error

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#380]
Brief Description: when get_followers is called, the server returns a 500 error with this message:
sqlite3.OperationalError no such column: serializedFollowers

Operating System (OS and version): Win10
OpenBazaar version: Master 1.1.4+

This can be reproduced every time on my local node, but does not affect the Vader test node.

**Comment by cpacia** [comment]
Did you run the followers PR on the same db then switch back? That PR runs a migration.

**Comment by jjeffryes** [comment]
Ah, that must be it.
