### ISSUE TITLE
Can not add certain moderators

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Server#383]
It has come to my attention that many people can not add me as a moderator (even those who have used me as a moderator in the past). I have verified this problem, and it turns out that you can not add me as a moderator using the manual guid, nor by clicking on the button "add as moderator". I can, however, add other moderators.

I have opened an issue thinking that it was a client problem (https://github.com/OpenBazaar/OpenBazaar-Client/issues/1469) but the response I got there was that the problem concerns the server. You can verify this problem by using my OpenBazaar GUID:

51df06a21ea821b337c85388bdd786757818e7f0 (@lunokhod)

I am running the server on OSX, I have no other connection problems, and I am using the latest commit 258a5e64130d6b247c0517005e974024bb22394a

The only "non standard" thing I am doing is specifying a specific network port with the command
~~~~
python openbazaard.py start -d -p 20000 -a 0.0.0.0
~~~~

**Comment by lunokhod** [comment]
This problem has mysteriously gone away, for the time being. I will re-open the issue if it reappears.

**Comment by danteweyl** [comment]
I have same problem and I can't add you for example.
Try adding me and see if it works: 403e140c2c74aab8bdbf5ea9a2ba426bb12a2fd5

**Comment by danteweyl** [comment]
@lunokhod can you reopen this case?
