### ISSUE TITLE
Add TLS support for API endpoints

### ISSUE THREAD

**Issue by stevenroose** [OpenBazaar/OpenBazaar-Server#385]
Brief Description: 
I see no option to secure the API endpoints (REST, WebSocket). So I assume in order to be secure while having the server running on a different machine, an HTTP reverse proxy is required..
It should be possible to specify certificates to use for secure HTTPS connections.

**Comment by hoffmabc** [comment]
There is TLS support already.

https://slack-files.com/T02FPGBKB-F0XK9ND2Q-fc5e6500a3

**Comment by stevenroose** [comment]
@hoffmabc 

Aha, that's useful, thanks!

However, I think I will still add a new issue in order for the instructions to be more easily accessible. The README file does not mention configuration files whatsoever, let alone SSL specifically.

**Comment by hoffmabc** [comment]
Works for me! Thanks.
