### ISSUE TITLE
Support using bitcoind/btcd for processing Bitcoin transactions

### ISSUE THREAD

**Issue by stevenroose** [OpenBazaar/OpenBazaar-Server#390]
Brief Description: 
Currently the server relies on libbitcoin nodes run by OB1. It should be possible to decide for oneself how to obtain Bitcoin-related data.

More specifically, since a lot of people are already running a Bitcoin node, it would be useful to allow these users to point openbazaard to their Bitcoin node instead of the libbitcoin node from OB1.

EDIT: It seems to already be possible to point to another libbitcoin node. I don't know if the libbitcoin API differs so significantly from bitcoind/btcd's API, but supporting other full node implementations is certainly a good thing.

**Comment by hoffmabc** [comment]
We don't have a driver layer yet for this, but maybe in the future. You can run your own libbitcoin-servers if you like as well as you mentioned.

**Comment by cpacia** [comment]
In the new go version there will be a bitcoin wallet interface that can be used to swap out the wallet for a different one.

**Comment by drwasho** [comment]
Closing this issue based on Chris' last comment. Work on the new repo can be found here: https://github.com/OpenBazaar/openbazaar-go

Thanks for your suggestion @stevenroose
