### ISSUE TITLE
The "Server Configuration" page always shows up. Cannot proceed.

### ISSUE THREAD

**Issue by Nd60** [OpenBazaar/OpenBazaar-Server#391]
Observed Behavior:
Every time I launch OpenBazaar it shows up the "Server Configuration" page. I have not set up a username nor a password, so I cannot proceed.

If I go to "View Debug Log" to investigate the issue, a dialog shows up with the message: "Error: EACCES: permission denied, open '/usr/share/openbazaar/resources/app/../OpenBazaar-Server//debug.txt'"

Expected Behavior:
I expect to first access the "Select your Language" page (step 1 of 10 of the wizard).

Operating System (OS and version): Ubuntu 14.04.4 LTS
OpenBazaar version: openbazaar_1.1.4_amd64.deb
Reproducible: Always 

![image](https://cloud.githubusercontent.com/assets/7318003/15125670/5e5198cc-162e-11e6-8b95-cf197aca2ecd.png)

**Comment by rmisio** [comment]
hmm... Are you sure this is a completely fresh install of the app? On a fresh install, you should be getting what you expect which is the "Select you Language"... page.

The only way I see that you could be getting the behavior you're experiencing is if you had already had a server set-up and then your localStorage was cleared (at least the part relevant to the server configuration). If that is somehow the case and you do want to start fresh, you could delete your database located in `~/.openbazaar`. But make sure you do indeed want to start fresh, as deleting the database will wipe all your data!

If you don't want to start fresh, there is a way we could set the password on the server via a config file. Let me know if that's the route you want to take.

**Comment by Nd60** [comment]
OK. Thanks! Deleting the `~/.openbazaar` folder worked like a charm.

Now I know what happened. It was a fresh install but I tried to install openbazaar without root access. So I typed on the terminal:

```
$ dpkg -i openbazaar_1.1.4_amd64.deb --force-not-root --root=$HOME
dpkg: error: requested operation requires superuser privilege
```
Running the previous command creates a folder on `~/.openbazaar`. If you later on run:
`sudo dpkg -i openbazaar_1.1.4_amd64.deb` or your double-click on openbazaar_1.1.4_amd64.deb file and reinstall, the mess created by the first dpkg is not fixed.

You can close this ticket. Thanks again.
