### ISSUE TITLE
Product Options (sizes, color etc..)

### ISSUE THREAD

**Issue by bitcoincoltd** [OpenBazaar/OpenBazaar-Server#398]
Are the product options not currently available in the openbazaar client?

Via the server API I have added options to a product, and when getting the contract details the options are successfully listed, example:

```
"options": {
                    "Size": [
                        "Small",
                        "Medium",
                        "Large"
                    ]
                },
```

However in the openbazaar client these options do not appear anywhere, including the store listing and the editor page.

**Comment by jjeffryes** [comment]
Setting options is currently not supported in the client, it will be in the future. 

The current data structure may not be the same once options are supported.

**Comment by drwasho** [comment]
@bitcoincoltd I'm closing the issue but please know that we just finished designing how to implement product options in OpenBazaar contracts; this will be supported soon.
