### ISSUE TITLE
Update price of a listing(contract)

### ISSUE THREAD

**Issue by sridhar87** [OpenBazaar/OpenBazaar-Server#409]
We are planning on integrating Open Bazaar into our store and one of our primary requirements in addition to creating listings(contract) is that we want to be able to update price of an existing listing(contract) dynamically based on available inventory size, etc.. I checked the code of the restapi.py on the server. There seems to be no API available to update a contract.

Is this something that is planned for any future releases?

Thanks in advance.
Sridhar

**Comment by sridhar87** [comment]
If this would be important for other users of the community, it would be good if you could come up with any suggestions/feedback on such an API. We would be happy to contribute this feature for the community.

**Comment by jjeffryes** [comment]
If you pass the contract_id parameter to the contracts call, it updates that contract with the new data you've sent.

**Comment by sridhar87** [comment]
@jjeffreys,

Thank you for your response. I did notice that we can pass the contract_id and it would update with the new data.

 I do not know how useful it would be for others, however, for our usecase, we would have only price and quantity of the inventory updating frequently. In this case, passing all data again to the contract is quite heavy for us. We have hundreds of thousands of products in our inventory and will be making price updates of that order or even much more every day. We still have no clue how scalable this platform is, we will be testing all this in the coming weeks.

Also, this feature - to update price and quantity, is almost a standard in many marketplaces - Amazon, eBay, for high volume sellers. We are one such seller who are testing out this OpenBazaar platform.

The light weight API I have in my mind is something like -
**update_inventory_status**_(contract_id, price, quantity)_ - which would update price and quantity of the given contract, leaving rest of the details unchanged.

Let me know your thoughts if this would be valuable API for the community(It is for us) or any suggestions you have about the API itself.

Thanks,
Sridhar

**Comment by jjeffryes** [comment]
Currently contacts don't have a quantity. We will be adding that in the future, when we do that we'll look at allowing partial updates to contracts. If we changed the contract api to only update the data that was sent (so you could send only the contract_id and the parameters you want to change) that would cover your scenario, correct?

**Comment by sridhar87** [comment]
Partial updates - this would be a great feature! And true, allowing partial updates would cover my usecase and much better than adding a new API.

Do you have any estimates on when we can expect this feature? We are not in a hurry, but just wanted to understand from a timeline perspective.

Thanks again for your reply. Very much appreciated.

**Comment by jjeffryes** [comment]
Inventory management is on our short term roadmap. https://trello.com/b/dF6ymHGU/openbazaar-high-level-roadmap
