### ISSUE TITLE
Add contract hash or last_modified field

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#411]
Right now contracts have a `contract_id` which allows for "listing malleability". To catch listing modifications, crawlers such as [duosear.ch](https://duosear.ch) have to repeatedly request the full contracts because `contract_id` does not change for all listing modifications. This repeated polling from crawlers can be a burden to vendors (and crawlers!), especially for stores with many listings.

I see two solutions for this:

- (ideal) Add a contract hash that covers the full contract
- (ok) Add a `last_modified` field

cc @hoffmabc @cpacia

**Comment by cpacia** [comment]
Where should this data go? The get_listings response?

**Comment by JustinDrake** [comment]
Yes, `get_listings` response.

**Comment by hoffmabc** [comment]
@cpacia I'll take this one.

**Comment by JustinDrake** [comment]
@hoffmabc Would be good to add a hash of the profile in `GET_LISTINGS`, so that we only do `GET_PROFILE` when the hash changes.

**Comment by JustinDrake** [comment]
@hoffmabc While it looks like the `last_modified` field has made it to `GET_CONTRACT`, I can't see it on `GET_LISTINGS` responses.

**Comment by JustinDrake** [comment]
For clarification, I'm referring to 1.1.7 clients. This prevents the scraper optimisation for Duo Search.
