### ISSUE TITLE
Include following status with contract returned via socket from get_homepage_listings

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/OpenBazaar-Server#418]
In the contracts that are returned via the socket after a socket request to `get_homepage_listings`, please include whether the owner of the contract is being followed by the requesting node or not.

![image](https://cloud.githubusercontent.com/assets/794517/15515261/1d89586e-21a2-11e6-8692-49eab598cd30.png)

This is needed so the UI can properly reflect the state of the Follow button on the Item in the grid view. Currently, the Discover page is getting this data by fetching the entire, un-paginated payload from get_followers, which is something we want to avoid (the node may have thousands of followers - it's the whole reason we put pagination in in the first place).

**Comment by rmisio** [comment]
ok, my mistake. Actually, the Discover UI is getting the data via a call to get_following, which AFAIK is not paginated. So... if we're thinking the number users a node will follow is unlikely to be too big, then I guess we could close this bug. But, if we ever find users following hundreds upon hundreds of other users, we may want to add pagination to get_following and then this ticket would be valid once again.

**Comment by jjeffryes** [comment]
I think adding pagination is something we're waiting on to see if it's necessary, because it does make things like this more difficult.  Let's cross that bridge when we need to.
