### ISSUE TITLE
STUN fails if re-binding too soon.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#44]
If the port is still mapped in the NAT and you restart, stun will fail because it's trying to re-bind the port too soon. This is problematic because we rely on the stun response to: 1) Get the IP address (which needs to be passed into the txrudp multiplexer) 2) Find the NAT type, which we need to determine the correct NAT traversal techniques. 

Need to figure out how to move forward with 1) and 2) if stun fails during binding.

**Comment by cpacia** [comment]
Just by diffing through the pystun source code it looks like the stun server is returning an unrecognized value.

```python
try:
                buf, addr = sock.recvfrom(2048)
                log.debug("recvfrom: %s", addr)
                recieved = True
            except Exception:
                recieved = False
                if count > 0:
                    count -= 1
                else:
                    retVal['Resp'] = False
                    return retVal
        msgtype = binascii.b2a_hex(buf[0:2])
        bind_resp_msg = dictValToMsgType[msgtype] == "BindResponseMsg"
```

The `KeyError` we are getting is because `msgtype` is not in the pre-defined list

I've tried other (google) stun servers, however, and get the same thing. Not sure if this library is functioning properly.

**Comment by weex** [comment]
How about retrying the STUN request a couple times if it fails in this way?

**Comment by cpacia** [comment]
Should be working ok now.
