### ISSUE TITLE
Cannot connect to default or remote server

### ISSUE THREAD

**Issue by eric116** [OpenBazaar/OpenBazaar-Server#447]
Brief Description:

Operating System: Ubuntu 16.04 LTS
OpenBazaar version: openbazaar_1.1.6_amd64.deb
Hardware: Dell Inspiron 7000 Series

Reproducible: Always

Steps to reproduce:
1. Open OpenBazaar and attempt to connect to either the localhost or a remote server.
2. Error message shows "Connection failed to [server name]"

Observed Behavior: Connection to server failes

Expected Behavior: OB should connect to server and show my store

It seems this issue first arose while I was editing my page. I noticed it was taking forever to save a listing, so I closed OB, and when I reopened, I couldn't connect to the server. For the first time, I got this message as soon as I opened OB:

```
Uncaught Exception:
Error: EIO: i/o error, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Console.log (console.js:39:16)
    at start_local_server (/usr/share/openbazaar/resources/app/main.js:143:13)
    at EventEmitter.<anonymous> (/usr/share/openbazaar/resources/app/main.js:190:7)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/usr/share/openbazaar/resources/electron.asar/browser/api/web-contents.js:128:25)
    at emitTwo (events.js:100:13)
```

![javascript error](https://cloud.githubusercontent.com/assets/10640906/16323684/efcbb23e-3969-11e6-818d-af0e709af765.png)

**Comment by eric116** [comment]
I found the insanely simple fix. Added -d -a 0.0.0.0 when launching server from terminal.

**Comment by jjeffryes** [comment]
For anyone checking this issue, be aware -a is the allow IP command, you can see all the commands in the readme for the server repo.

https://github.com/OpenBazaar/OpenBazaar-Server

Setting -a to 0.0.0.0 will allow any ip to connect to your node. This means any client that has your username and password can run your node.

It's better to use -a with the ip address of the computer your client is running on. While it's unlikely someone would have your credentials and try to access your node, it's a good idea to be careful.
