### ISSUE TITLE
Multiple Stores on Same Server

### ISSUE THREAD

**Issue by no1youknowz** [OpenBazaar/OpenBazaar-Server#449]
OB 1.1.7.  

Client running on Windows.
Server running on Linux.

I'm trying to get multiple servers running using NAT.

I create a new instance with:

    python openbazaard.py start -a 0.0.0.0

I can connect fine and set it up.

I then shutdown the instance and run it again with:

    python openbazaard.py start -a 0.0.0.0 --restapiport 28469 --websocketport 28466 --heartbeatport 28470

I now can't connect to it.

**Comment by Rocks333** [comment]
I imagine except changing the port you would have to change the linux user, so it creates new folder in the user's home directory with the individual settings for each store.

And then run it with changed ports. 
Please let me know how it goes, since I'm also interested in that.

**Comment by no1youknowz** [comment]
> I imagine except changing the port you would have to change the linux user, so it creates new folder in the user's home directory with the individual settings for each store.

Can you clarify with this?  

Because I was under the assumption that changing the data folder in ob.cfg, sets the individual store settings.

I clarified this because if I launch each store separately without the port changing.  I connect to a unique store.

I also checked the users home dir, I found nothing related to OB.

**Comment by no1youknowz** [comment]
Also, as a follow up:

When I do

    python openbazaard.py start -a 0.0.0.0 --port XXXX

The whole application locks up at trying to identify the NAT configuration.

**Comment by Rocks333** [comment]
I was unaware that you can set different settings folder in ob.cfg. Then this might be a way too.
But if you want try launching them from separate users just to see if it helps.

I was under the impression that you are able to start the instances under different ports? Just that they were using the same settigns folder thus resulting to the same store?

**Comment by no1youknowz** [comment]
> I was unaware that you can set different settings folder in ob.cfg. Then this might be a way too.
But if you want try launching them from separate users just to see if it helps.

I think I am a bit ahead of you, in terms of trying things out.  But thanks for replying anyways.

> I was under the impression that you are able to start the instances under different ports?

You can, but it's clearly not working.

> Just that they were using the same settigns folder thus resulting to the same store?

They are unless you change the data folder.

Again, thanks for replying.  But really waiting someone from the dev team to confirm.

Thanks

**Comment by no1youknowz** [comment]
I know devs are busy an all.  But even hanging out on slack didn't get an attention...

Now that 2.0 is coming out.  Going to wait for that and will try this again!

Closing for now.
