### ISSUE TITLE
Cannot connect to 1.1.7 default server on Win 10

### ISSUE THREAD

**Issue by Kaden14** [OpenBazaar/OpenBazaar-Server#453]
Guys, I have tried connecting to the default locahost server, but to no avail.
Then I tried creating my own server and changed the ob.cfg file to correspond with the details of the newly created server... no luck
I installed 1.1.7 hoping this would be fixed - nope.
I tried running openbazaar.exe and a little black box (command prompt, but it was part of the app) popped up for 1 second and it said this... ( i had to screen shot very quickly and crop) 
![thishappens](https://cloud.githubusercontent.com/assets/7027695/16491117/469a899a-3ea2-11e6-9321-cd02dd9d6290.png)

so, I cannot connect and I dont know if anybody else is having this issue...

**Comment by Kaden14** [comment]
Oh, this is the Python Error Log...
![pythonerrorlog](https://cloud.githubusercontent.com/assets/7027695/16491167/70406378-3ea2-11e6-9aa5-beb939ccc809.png)

**Comment by Kaden14** [comment]
SOLVED!

**Comment by HappyHead** [comment]
how'd u solve it? I have the same problem
