### ISSUE TITLE
"sudo python openbazaard.py stop" doesn't stop the server on Ubuntu

### ISSUE THREAD

**Issue by Rocks333** [OpenBazaar/OpenBazaar-Server#457]
Fresh ubuntu 14.04 install. Fresh install of OB

`~/OpenBazaar-Server$ sudo python openbazaard.py stop
OpenBazaar server stopping...                                                                                                        
pidfile /tmp/openbazaard.pid does not exist. Daemon not running?`

and then it's still in the processes viewable in htop

running the command few times doesn't help

**Comment by Rocks333** [comment]
nobody?

**Comment by hoffmabc** [comment]
If you're trying to stop it and the pid is missing and there's no process then it's stopped. I am not sure what you're asking for.

**Comment by Rocks333** [comment]
There IS process and it is working. I can even connect to the server.
I'm asking how to effectively stop it and why the stop doesn't work I guess.

**Comment by Rocks333** [comment]
so no one else is unable to stop it with "sudo python openbazaard.py stop" ?

**Comment by hoffmabc** [comment]
That's because you're running it in daemon mode yo. I'm closing this as it works intended if you start in daemon mode. Otherwise no .pid file gets created.
