### ISSUE TITLE
Error installing on NixOs

### ISSUE THREAD

**Issue by diegueins680** [OpenBazaar/OpenBazaar-Server#458]
Brief Description:
I get the following error when trying to build OpenBazaar-Server on NixOs:
http://pastebin.com/AMs9XZtg

Operating System (OS and version): 
$ uname -a
Linux jet-nixos 4.4.13 #1-NixOS SMP Wed Jun 8 01:14:51 UTC 2016 x86_64 GNU/Linux

OpenBazaar version: 
v0.2.1 

Hardware: 
http://pastebin.com/vWfPFQ0G

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. $  git checkout v0.2.1
2. $  nix-shell -p nodejs electron python35Packages.pip gcc libffi python
3. $ pip install -r requirements.txt

Observed Behavior:
http://pastebin.com/AMs9XZtg

Expected Behavior:
OpenBazaar-server gets installed

**Comment by hoffmabc** [comment]
I'm not familiar with NixOS and we don't really support it directly. This sounds like some compatibility with the distribution and python libraries we use. I'm making as Won't Fix because it is out of scope for us to address this.
