### ISSUE TITLE
Item description adds "ob://" to any # or @ symbol

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/OpenBazaar-Server#462]
Tried saying "#4,000" and my twitter "@MatthewZipkin" in item description.
Both of those expressions got tweaked like: "ob://@MatthewZipkin" and "ob://#4,000"

**Comment by jjeffryes** [comment]
Within the OpenBazaar app, any word with a @ in front of it is considered a handle link, and can be used to navigate to a user's page. 

Words with a # in front of them are considered search terms, and will link to that search term.

If you want to have a link to twitter, you can paste the URL, which will automatically be converted to a clickable link, or use the HTML code for a link.
