### ISSUE TITLE
Unable to run on ubuntu 15.04

### ISSUE THREAD

**Issue by tranqy** [OpenBazaar/OpenBazaar-Server#468]
Brief Description: When trying to run python openbazaar.py start I am getting the error

ImportError: No module named sanitizer

When importing bleach.  

Operating System (OS and version): Ubuntu
OpenBazaar version: Master
Hardware: LXD VM

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Clone
2. Install reqs
3. Attempt to start

Observed Behavior:
Error 

Expected Behavior:
OpenBazaar would start

Additional info (links, images, etc go here):
I was able to get things to run by bumping the bleach version number to 1.4.3. 

Full stack below.

Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/root/OpenBazaar-Server/api/ws.py", line 15, in <module>
    from api.utils import smart_unicode, sanitize_html
  File "/root/OpenBazaar-Server/api/utils.py", line 1, in <module>
    import bleach
  File "/usr/local/lib/python2.7/dist-packages/bleach/**init**.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named sanitizer

**Comment by Dako300** [comment]
This was broken in the lastest update of html5lib. Run this to clock it back

sudo pip install html5lib==0.999

**Comment by lubah** [comment]
installing html5lib==0.999 initially worked for me but now upon reboot its complaining about this: 

sudo -H python /home/ubuntu/OpenBazaar-Server/openbazaard.py start -da 0.0.0.0
Warning: configuration file not found: (ob.cfg), using default values
Traceback (most recent call last):
  File "/home/ubuntu/OpenBazaar-Server/openbazaard.py", line 11, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/home/ubuntu/OpenBazaar-Server/api/ws.py", line 16, in <module>
    from config import DATA_FOLDER, str_to_bool
  File "/home/ubuntu/OpenBazaar-Server/config.py", line 163, in <module>
    DATA_FOLDER = _platform_agnostic_data_path(cfg.get('CONSTANTS', 'DATA_FOLDER'))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'CONSTANTS'

**Comment by Dako300** [comment]
Dont run it as root

**Comment by Dako300** [comment]
nevermind the prev comment, run it in the local directory

**Comment by hoffmabc** [comment]
Closing.
