### ISSUE TITLE
Issue Installing OpenBazaar-Server in CentOS

### ISSUE THREAD

**Issue by gdlt88** [OpenBazaar/OpenBazaar-Server#470]
Brief Description: 

Hi, I'm trying to install OpenBazaar in CentOS. Command pip install -r requirements.txt ran well. However, I get an error when running python openbazaard.py start. The error displayed is:

Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/home/publicuser/OpenBazaar-Server/api/ws.py", line 15, in <module>
    from api.utils import smart_unicode, sanitize_html
  File "/home/publicuser/OpenBazaar-Server/api/utils.py", line 1, in <module>
    import bleach
  File "/usr/lib/python2.7/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named sanitizer

Please, if anyone can help me with this.

Thanks

Operating System (OS and version): CentOS 7
OpenBazaar version: Latest version

**Comment by hoffmabc** [comment]
We don't test on centos so not sure specifically but certainly doesn't seem like bleach is installing properly.

**Comment by gdlt88** [comment]
I resolve the issue. Like you said, it was a problem with bleach. I updated using pip install -- upgrade bleach and now it works.

Thanks
