### ISSUE TITLE
OpenBazaar's Apis Authorization Error, Permission Denied

### ISSUE THREAD

**Issue by gdlt88** [OpenBazaar/OpenBazaar-Server#471]
Brief Description: I configurated my OpenBazaar Server and Client successfully. I can log in and see my profile, products,etc. However, when I try to use the APIs, it gives me an authorization error - permission denied. I don't know why does this happen. Do I have to open the port in the firewall?

Thanks.

Operating System (OS and version): CentOs
OpenBazaar version: Latest

**Comment by luandro** [comment]
Same here.

OSX

**Comment by hoffmabc** [comment]
You need to issue a /login call before you can request from the API directly.

See here:
https://www.reddit.com/r/OpenBazaar/comments/4dqwf2/rest_api_authentication/
