### ISSUE TITLE
OB server behind a hostname

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/OpenBazaar-Server#478]
I switched from amazon AWS to rpi3 which sits behind a dynamic address. I'm using dynamic DNS so a hostname points to this dynamic IP(s) and the DNS updates every time my IP changes. This works without any issues.

The problem is (I think) that instead of my hostname, my IP address is stored in DHT which causes issues the moment my rpi3 gets a new IP address (and user's DHT still points to the old one). This causes me to appear offline for duosear.ch and some others.

I'd suggest a hostname is stored in DHT instead of IP when the server runs on one. This information is available in server settings.

**Comment by hoffmabc** [comment]
I'm marking this as Won't Fix because we won't be addressing this in the 1.x code.
