### ISSUE TITLE
unable to run openbazaar on windows 10 in any way

### ISSUE THREAD

**Issue by jkokorian** [OpenBazaar/OpenBazaar-Server#484]
- Tried to install openbazaar with both the 64-bit and 32-bit installer executables => installer crashed immediately as described here: https://github.com/OpenBazaar/OpenBazaar-Installer/issues/47
- Tried to run the server in a docker container => [0mMakefile:14: recipe for target 'pycheck' failed
- Tried to install using pip: miniupc failed to compile

Any suggestions what I could try next? I'm out of ideas

**Comment by jkokorian** [comment]
ok, I got the go implementation of the server to run. Now let's see if the desktop client will install...

**Comment by jkokorian** [comment]
Nope, the go client won't install because of a missing dependency 'npmlog'. Turns out to be an npm issue: https://github.com/npm/npm/issues/10409
I tried the things suggested in the thread, but they didn't work for me. I've tried it in the windows terminal and in the bash terminal on the windows subsystem for linux. Nothing works.

**Comment by hoffmabc** [comment]
Please try on 1.1.8 release and re-open if necessary.

**Comment by jkokorian** [comment]
works now, nice!
