### ISSUE TITLE
Bad handling of nodes with same ip

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#49]
Currently, the code wont save a node in the routing table if it's guid already exists in the table, but it does save it has a different guid (but same IP). 

A bug has cropped up during testing where people delete their db to create a new guid and then reconnect to the network. We end up with multiple nodes from the same IP in the routing table. This sometimes causes nodes to send duplicate messages to that IP.

Furthermore, it doesn't seem that the copies of the node are removed when `removeContact` is called.

If we prevent nodes with the same IP from being added to the routing table, then someone would be prevented from running two nodes on the same computer (maybe that's a good thing?). 

Alternatively we can improve the logic of `removeContact` so that nodes don't persist in the routing table after they've disconnected.

**Comment by gubatron** [comment]
>If we prevent nodes with the same IP from being added to the routing table, then someone would be prevented from running two nodes on the same computer (maybe that's a good thing?).

I don't think that's a good thing.

You could be running 10 nodes from the same network, each for a different store, all having the same public IP address.

This could very well happen if people are running nodes from work/university/school.

**Comment by gubatron** [comment]
>Alternatively we can improve the logic of removeContact so that nodes don't persist in the routing table after they've disconnected.

Do you have some sort of `BYE` message or some sort of Store shutdown procedure, so a node can tell everyone she's leaving?

**Comment by cpacia** [comment]
> Do you have some sort of BYE message or some sort of Store shutdown procedure, so a node can tell everyone she's leaving?

Yes, but the above problem wouldn't happen if everyone shutdown cleanly. But that hasn't been the case.

> You could be running 10 nodes from the same network, each for a different store, all having the same public IP address.

But they would have different ports though right? I would do it so that it only allows one (ip, port) tuple in the routing table.

**Comment by gubatron** [comment]
Yes, they'd each have a different outgoing port.

Not sure if you're keeping a mapping of both internal IP:PORT and external IP:PORT, sort of like your own NAT table and if that'd in any way would help. 

So maybe the way you do it is you keep those 2 EndPoint objects. where:

```python
class EndPoint:
   ipAddress
   port
```
and if you have something like a `Peer` class it'd have:
```python
class Peer:
  ...
  internalEndpoint # : EndPoint  #10.0.0.23:7784
  publicEndpoint # EndPoint    #57.43.2.45:8831
  ...
```

It would be probably useful to run searches on the local network so these nodes on the same network are able to support each other in whatever way they can.

And stay away from evil tuples! Use objects.
