### ISSUE TITLE
Config issue - why isnt my listing accessable?

### ISSUE THREAD

**Issue by sebastianheyn** [OpenBazaar/OpenBazaar-Server#491]
Hi,

my server runs on a debian box, all 3 ports are forwarded to that machine. The listing is available on bazaarbay - however when I try to access it form another machine it isnt accessible. 

Any thoughts?

http://bazaarbay.org/e24087a63d7030ce16b5e069adf9ced81b2f7d4f/listing/3c3fe931c50ee172c27d28d327b9394aa5c13b32

**Comment by sebastianheyn** [comment]
seems like restarting the server helped. is there a need to regularily restart the server?

**Comment by bdunbar** [comment]
Yes.

**Comment by hoffmabc** [comment]
Unfortunately yes from time to time some installs require bouncing from time to time. Many folks are using a cron job to periodically do this.

**Comment by sebastianheyn** [comment]
pointing this out in the docs would be a good thing, or is the focus the new go-based server everyone is waiting for? 

is it safe to restart the machine? I saw that the init waits for the process to finish before rebooting - or do you suggest a certain signal to be sent to the bazaar-server?

**Comment by hoffmabc** [comment]
Focus is on the new go server but we will be updating documentation.
