### ISSUE TITLE
rest API get/post settings are inconsistent

### ISSUE THREAD

**Issue by richardschneider** [OpenBazaar/OpenBazaar-Server#495]
`GET .../settings` returns a `blocked_guids` field, whereas `POST .../settings` expect a `blocked` field.

Can we decide on one name.

See the [GET](https://github.com/OpenBazaar/OpenBazaar-Server/blob/6efb928a4e6a3419de3cce0ed76a4ce88ee2ec2b/api/restapi.py#L932) and [POST](https://github.com/OpenBazaar/OpenBazaar-Server/blob/6efb928a4e6a3419de3cce0ed76a4ce88ee2ec2b/api/restapi.py#L890) code.

**Comment by cpacia** [comment]
@richardschneider I'm not putting too much more work into the api for this version. The api for 2.0 is where most of the development is happening.
