### ISSUE TITLE
Give preference to long lived nodes

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/OpenBazaar-Server#5]
One traditional way of preventing flooding attacks (where an attacker issues a bunch of STORE commands and causes nodes to run out of storage capacity) is to give preference to long lived nodes. 

In the event a node runs out of capacity it should start dropping stored values of short lived nodes first. 

Since we will likely have some kind of rate limiting built into the protocol (see issue #3), the only way to flood the dht would be from many nodes (a botnet for example). But more likely than not, all those botnet nodes will have been recently started making the attack unsuccessful. The attacker would have to keep them running a long time (implying that the owners of those computers never turn them off or restart) in order to have success. 

Since vendors, who are the only ones storing data in the dht at the moment, are online most of the time anyway, this should work fairly well. 

The only concern might be if most of the nodes in the network are buyers (very short lived nodes), then they can't distinguish between honest nodes and an attacker and may drop stored values from honest nodes. Given a k value of 20, it's likely that honest vendors will see their data persist if only on a few nodes. But it might require more tuning of the k value to ensure that in the face of a flooding attack.

**Comment by gubatron** [comment]
so if I were to attack and saw this, I'd make sure to have my nodes running for a long time before starting the flood.

**Comment by cpacia** [comment]
Yeah it isn't completely perfect, but it's better than nothing. Also consider that if you had a few long lived nodes and started a flooding attack, your IPs would get banned pretty quickly and the damage would be limited.

You would basically need control of a very large botnet where computers remain online for long periods of time. And even then, those nodes IPs will get banned as soon as they start the flood. The attacker would just need to hope the combined messages that do get through before getting banned are enough to be disruptive. 

I guess that's an empirical question.

**Comment by hoffmabc** [comment]
I think the idea is to make it financially or logistically too hard to pull off or sustain. With IPv6 the changing of IPs could hamper the ban method, but that's looking down the road a ways. This problem is common in smaller networks as they don't have strength in numbers and are easy to game or manipulate. Perhaps there's some kind of financial incentive we can make users commit to if they go above a certain size of data. Like have nodes return a message saying basic data storage full, if you need more space you got to pay.

**Comment by gubatron** [comment]
great explanation @cpacia. I guess the only attacks possible then would be very unlikely, by individuals with lots of resources, and sort of a one off type of thing every few months. This def. sounds like a good defense strategy against sustained DDOS.
