### ISSUE TITLE
Version reported is hard-coded

### ISSUE THREAD

**Issue by sgornick** [OpenBazaar/OpenBazaar-Server#503]
Brief Description: Running help reports a version number, but it is inconsistent with the version being run.

OpenBazaar version: 0.2.3

Reproducible: Always

Steps to reproduce:
1. $ python openbazaard.py  --help

Observed Behavior:
OpenBazaar-Server v0.2.1

Expected Behavior:
OpenBazaar-Server v0.2.3

Additional info (links, images, etc go here):
It's hardcoded! 

"description='OpenBazaar-Server v0.2.1',"

https://github.com/OpenBazaar/OpenBazaar-Server/blob/903ac7f157aa6a67c719affcbcacef1b325b09d1/openbazaard.py#L217

**Comment by hoffmabc** [comment]
This fix has been merged. https://github.com/OpenBazaar/OpenBazaar-Server/commit/eb48419a10d47aa6aa3105d5d93387140eb5225c
