### ISSUE TITLE
Sorting a store's listings by Date (newest) and Date (oldest) would be useful

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Server#512]
@rmisio mentioned we need a server issue for this too.

@cpacia see https://github.com/OpenBazaar/openbazaar-desktop/issues/217 for more information

**Comment by rmisio** [comment]
@morebrownies: Lol, but we would need the field in the v2 server!

**Comment by morebrownies** [comment]
![sdg](https://cloud.githubusercontent.com/assets/13066886/21281493/251798a0-c3a2-11e6-89d5-07ec53157da1.jpg)
