### ISSUE TITLE
product search server

### ISSUE THREAD

**Issue by xxtotoxx** [OpenBazaar/OpenBazaar-Server#548]
Brief Description: 

I did not quite understand how to organize or add a product search server.
For example, conditionally, I want users of one country to be able to search on this server and it also displayed in the panel along with OB1, DUO, BKB RAW
Sorry, I'm writing translator's chez.

**Comment by tyler-smith** [comment]
Hi @xxtotoxx.

Apologies if I'm misunderstanding, but I believe you're asking how to set up a search provider that works in the client. To do this, you need to set up an API server compatible with the format outlined in OBIP2: https://github.com/OpenBazaar/obips/blob/master/obip-0002.md

After you've done that your endpoint should work in the client if you manually add it with the "+" icon next to the existing search providers. After you have finished and tested it by adding it manually, we can review it for inclusion by default in the client.

For example, here is our OB1 API: https://search.ob1.io/search?q=*&pretty

And this is BlockBooth, and up and coming search engine: https://search.blockbooth.com/api

**Comment by tyler-smith** [comment]
@xxtotoxx I just realized which repo this issue is in. This repository is deprecated. For the new server please use https://github.com/OpenBazaar/openbazaar-go and for the new client use https://github.com/OpenBazaar/openbazaar-desktop
