### ISSUE TITLE
User friendly GUID creation

### ISSUE THREAD

**Issue by unsystemizer** [OpenBazaar/OpenBazaar-Server#63]
* GUID creation is slightly expensive (in terms of CPU time)
* Because of that, it takes a loooong time to create a GUID on ARM based devices (mine's been generating for 10+ minutes now, and it's not done yet (number 2, python, is the GUID gen thing)

![image](https://cloud.githubusercontent.com/assets/13134193/10863279/c84a2c02-8002-11e5-934e-39c41d02c52f.png)

To me this doesn't matter, I can leave it run overnight, but  I think some users would just give up so the question is what to do about this, if anything.
One way to improve this would be to install and generate elsewhere, then migrate that on ARM. That's too complicated for Average Joe.
Another would be to adjust the GUID generating routine to take it easy on ARM. But one also has to wonder why spammers wouldn't adjust the code to treat Intel CPUs as ARM.

**Comment by cpacia** [comment]
It's supposed to be an average of 30 seconds to 1 minute on a typical cpu. I suppose it's possible it could take 10 minutes, but should be rare. If you run key gen multiple times you will get a better idea of how long it takes on an ARM.

**Comment by hoffmabc** [comment]
Also I would expect your cpu to spike during this process. It's sitting at 3%. That says somethings up to me.

**Comment by hoffmabc** [comment]
Nevermind, I just saw that's memory. I'm not an idiot.

**Comment by unsystemizer** [comment]
@cpacia on a typical x86 yes, but ARM is crap and this was on a less crappy model. 
In any case, if (say) 15 minutes is still considered acceptable, we can simply document that on systems with slower processors the GUID creation step can take up to 20 minutes, just to avoid users interrupting the process because "OB froze on me".

**Comment by unsystemizer** [comment]
>  If you run key gen multiple times you will get a better idea of how long it takes on an ARM.

Why would it be different between runs? The time displayed is how much CPU time it took. If the system is busy I would wait even longer as the GUID generator would have to wait to get scheduled, but that is not our concern.

On Raspberry Pi B it takes at least 1 hour to generate a GUID (I stopped watching after 60 mins).

![image](https://cloud.githubusercontent.com/assets/13134193/10865618/fe756262-804b-11e5-9c9a-779585e5eb45.png)

**Comment by cpacia** [comment]
> Why would it be different between runs?

The generation is a proof-of-work. You could find a valid key on the first attempt or the 1 millionth.

**Comment by unsystemizer** [comment]
Ah, from that perspective, sure.

RPi 2: 14 mins on average (13 tries).
RPi B: 55, 70 minutes.

It seems that most Pi owners won't see their GUID generated within 10 mins.

**Comment by gubatron** [comment]
is the key generated by OpenBazaar in python?

**Comment by gubatron** [comment]
nvm, it's already generated in C, nice!
https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/keyutils/guidc.c

**Comment by cpacia** [comment]
> nvm, it's already generated in C, nice!

At the moment I'm not using the C code because people had a hard time installing it. 
But even doing it in python relies mostly on the crypto library which is also C so it turns out the straight C code is only about a 10-15% speed up.

**Comment by hoffmabc** [comment]
I think at this point in time I'm not really that tore up about a small ARM or RPi device taking a while to generate a GUID. Giving a warning for those devices is probably a very reasonable request and better than just dropping back and taking forever.

**Comment by cpacia** [comment]
Going to close this for now since aren't going to do anything about it for version 1. Maybe later we can make a tool to generate a key on a separate machine and import it into the server.
