### ISSUE TITLE
Windows build trouble with miniupnp

### ISSUE THREAD

**Issue by unsystemizer** [OpenBazaar/OpenBazaar-Server#66]
I can't build on Windows with MSVC. It seems miniupnp building is supported only with Cygwin, and that's a whole new can of worms. 
What's going to be supported - Cygwin or MSVC?

**Comment by hoffmabc** [comment]
@yagoulas is reworking the script to support windows. Right now we are testing it out using msysgit bash command line.

**Comment by hoffmabc** [comment]
miniupnpc compiles fine with 32-bit for me but we are working on getting 64-bit possible as well.

**Comment by unsystemizer** [comment]
Okay. msysgit is a Cygwin-like approach so that's not unexpected and also encouraging to hear. 
I remember the "old' builds were MSVC based so I thought this one will use MSVC as well.

**Comment by hoffmabc** [comment]
Well @yagoulas made those as well, but he just started helping out on this Friday so we should see more progress this week. He can also answer more questions. I have been up to this point only testing this script on OSX as per the README.

**Comment by yagoulas** [comment]
Building with MSVC is still supposed to work more or less. How exactly were you trying to build it?

**Comment by unsystemizer** [comment]
Installed python 2.7.10, installed the MSVC thing for Python, then upgraded pip and ran `pip install -r requirements.txt` and it choked on the last of 12 requirements (miniupnp). If you look on the Web there are binaries (if that was a dependency, maybe we could remove miniupnp from `requirements.txt`?), but as far as building on Windows goes it's only supported with GNU make.

**Comment by yagoulas** [comment]
I see what you mean. We hackfixed the problem by using this command:
`python -m pip install 'https://github.com/yagoulas/miniupnp/zipball/msvc_miniupnpc'`. Of course this requires that I keep this branch up to date with the miniupnpc project. If you run this command and then `pip install -r requirements.txt`, it should work fine.

**Comment by hoffmabc** [comment]
Is this something that @miniupnpc could accept into their branch?

**Comment by unsystemizer** [comment]
On Win 7 x64 with that MSVC addon for Python 2.7:

```
C:\Python27\Scripts>python -m pip install https://github.com/yagoulas/miniupnp/zipball/msvc_miniupnpc
Downloading/unpacking https://github.com/yagoulas/miniupnp/zipball/msvc_miniupnpc
  Downloading msvc_miniupnpc (107kB): 107kB downloaded
  Running setup.py egg_info for package from https://github.com/yagoulas/miniupnp/zipball/msvc_miniupnpc
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-gzdngr6d-build\setup.py", line 29, in <module>
        subprocess.call([vcbuild, 'miniupnpc.vcproj'])
      File "C:\Python34\lib\subprocess.py", line 537, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Python34\lib\subprocess.py", line 858, in __init__
        restore_signals, start_new_session)
      File "C:\Python34\lib\subprocess.py", line 1111, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "C:\Users\user\AppData\Local\Temp\pip-gzdngr6d-build\setup.py", line 29, in <module>

    subprocess.call([vcbuild, 'miniupnpc.vcproj'])

  File "C:\Python34\lib\subprocess.py", line 537, in call

    with Popen(*popenargs, **kwargs) as p:

  File "C:\Python34\lib\subprocess.py", line 858, in __init__

    restore_signals, start_new_session)

  File "C:\Python34\lib\subprocess.py", line 1111, in _execute_child

    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

But never mind, I'm okay with MinGW or other approaches.

I agree with Brian's idea - it would be nice if upstream could accept your changes.

**Comment by cpacia** [comment]
The windows installer should be able to handle miniupnpc when it's ready. For now there is the noupnp branch for people who just want to skip it.
