### ISSUE TITLE
Make sure strings are Unicode in the restapi

### ISSUE THREAD

**Issue by jojva** [OpenBazaar/OpenBazaar-Server#74]
When they are read inside restapi.py, incoming strings are in the 'bytes' format.
What I call incoming strings are e.g. 

    u = objects.Profile()
    u.name = request.args["name"][0]

Protobuf's type checker will check whether ```request.args["name"][0]``` if of ```bytes``` type. When it detects that it is, it fails when the string contains non-ascii characters, like 'é' with the following exception : "has type bytes, but isn\'t in 7-bit ASCII 'encoding. Non-ASCII strings must be converted to unicode objects before being added.".
That prevents entering any non-ascii description everywhere.

**Comment by cpacia** [comment]
so it should be:
```python
u.name = request.args["name"][0].encode("utf-8")
```
?

**Comment by jojva** [comment]
From what I gathered on various websites, the consensus for a maintainable code is to use Unicode (decoded strings) everywhere, and encode when you have to display, save, broadcast, basically when it leaves the app. This looks like a nightmare to fix when it's too late, so this should be tackled as soon as possible imho.
So it should be **decode** actually:
```python
u.name = request.args["name"][0].decode("utf-8")
```
I'm making the pull request right away.

**Comment by drwasho** [comment]
@cpacia do we want to close this?
