### ISSUE TITLE
Authentication on REST API so we can support remote stores securely

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#76]
I think we need to add some secure authentication to remote OpenBazaar-Server instances and this will allow us to host them anywhere.

**Comment by drwasho** [comment]
Hell yes.

**Comment by SamPatt** [comment]
+1

And more broadly speaking, we need to consider any other security implications of having a server on one machine (likely a VPS) and the client on another (likely the users' home computer).

**Comment by cpacia** [comment]
Need someone with an ssl cert to test out the rest and websockets api.

**Comment by cpacia** [comment]
Complete
