### ISSUE TITLE
Message "FAIL: Detected 3 files with errors." when no errors where printed

### ISSUE THREAD

**Issue by yurivict** [OpenBazaar/OpenBazaar-Server#88]
Log only has 3 warnings:
api/ws.py: 20: [W:no-init] -- Class has no __init__ method
api/wsclient.py: 11: [W:no-init] -- Class has no __init__ method
bootstrap.py:  6: [W:redefined-outer-name] -- Redefining name 'use_testnet' from outer scope (line 29)

So I can't build it.

**Comment by cpacia** [comment]
You don't need to run make to run the server. It's only used for running tests.
