### ISSUE TITLE
There MUST be an easy way to install it

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#97]
Let's say I tell a friend:

- Hey, did you heard about OpenBazaar, a peer to peer shopping platform where you can buy/sell anything?
- Nope, but sounds very interesting. I'll try it out. How to install it?
- Follow these instructions https://github.com/OpenBazaar/OpenBazaar-Server/wiki/Installing-pynacl-on-Windows#instructions
- Are you kidding me? I am not a sys admin ...

*(sorry for my English if there are mistakes)*

**Comment by hoffmabc** [comment]
There is an installer. Http://github.com/OpenBazaar/OpenBazaar-Installer and it will support Windows. I'm closing this because it's one of our highest priorities and being tracked there.

**Comment by moldcraft** [comment]
Thank you
